samvera/bulkrax

app/factories/bulkrax/collection_factory.rb, app/factories/bulkrax/work_factory.rb, app/jobs/bulkrax/import_work_collection_job.rb, app/jobs/bulkrax/import_work_job.rb, app/jobs/bulkrax/importer_job.rb, app/models/bulkrax/csv_collection_entry.rb, app/models/bulkrax/csv_entry.rb, app/models/bulkrax/entry.rb, app/models/bulkrax/importer.rb, app/models/bulkrax/oai_entry.rb, app/models/bulkrax/oai_set_entry.rb, app/parsers/bulkrax/csv_parser.rb, app/parsers/bulkrax/oai_dc_parser.rb, db/migrate/20190715161939_add_collections_to_importer_runs.rb, db/migrate/20190715162044_change_collection_ids_on_entries.rb, lib/bulkrax.rb, spec/factories/bulkrax_importers.rb, spec/fixtures/csv/good.csv, spec/fixtures/csv/ok.csv, spec/jobs/bulkrax/importer_job_spec.rb, spec/models/bulkrax/csv_entry_spec.rb, spec/models/bulkrax/importer_spec.rb, spec/test_app/db/schema.rb
Fixes #9
* Moves Collection Creation to a factory / job. 
* Ensures collections get created before works.
=> Refactor collections

app/matchers/bulkrax/application_matcher.rb, app/models/bulkrax/oai_entry.rb, app/parsers/bulkrax/csv_parser.rb
* preface LanguageList with :: and add the require to the matcher not the entry
* add contributing institution to collection in a clean way
=> Two small bug fixes

app/parsers/bulkrax/csv_parser.rb
In the CSV parser, the collection name will be repeated on each line, leading to multiple create collection jobs.
When running multiple concurrent jobs, these will run concurrently leading to errors in trying to create the collection at the same time.
This PR grabs a list of collections from the CSV and only creates unique ones.
=> CSV create collections - avoid duplicate calls

app/parsers/bulkrax/csv_parser.rb, app/parsers/bulkrax/oai_dc_parser.rb
Just to be extra sure the collections are created before works, use peform now
=> use perform now in collection jobs

app/models/bulkrax/oai_entry.rb
all others appear to be in ATLA code now
=> removed last contributing institution reference

README.md, lib/generators/bulkrax/install_generator.rb, lib/generators/bulkrax/templates/README, lib/generators/bulkrax/templates/app/models/bulkrax/concerns/has_local_processing.rb, lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
Adds an install generator:
```
rails generate bulkrax:install
```
=> Add an install generator

Gemfile, lib/generators/bulkrax/install_generator.rb
Switches to a PR of willow_sword where the pin to rails 5.1.6 has been relaxed.
=> Switch to fork of willow_sword

app/models/concerns/bulkrax/has_matchers.rb, spec/models/bulkrax/entry_spec.rb
field_to was still returning an empty array
=> Fix field_to 

app/views/bulkrax/importers/index.html.erb
=> I35 create importer showpage links

app/models/bulkrax/exporter.rb, app/models/bulkrax/importer.rb, app/models/concerns/bulkrax/importer_exporter_behavior.rb, app/parsers/bulkrax/csv_parser.rb, app/views/bulkrax/exporters/index.html.erb, app/views/bulkrax/importers/index.html.erb, db/migrate/20191203225129_add_total_collection_records_to_importer_runs.rb, db/migrate/20191204223857_change_total_records_to_total_work_entries.rb, spec/factories/bulkrax_exporter_runs.rb, spec/factories/bulkrax_importer_runs.rb, spec/models/bulkrax/importer_spec.rb
WIP. Still need to increment total_collection_records in increment_counters(index)
=> i34 changed records to entries and added total collections and works

app/controllers/bulkrax/importers_controller.rb, app/views/bulkrax/importers/show.html.erb
Note: I'm not sure what `<p id="notice"> <%= notice %>` does and if it should be inside or outside the main body content.
=> i36 added showpage breadcrumbs and minor styling

app/parsers/bulkrax/csv_parser.rb, app/views/bulkrax/importers/index.html.erb
missed a total_records and total_collection_entries
=> typos and missed a column

app/views/bulkrax/importers/show.html.erb
Added glyphicons based on status:
=> I38 importer showpage step three

app/views/bulkrax/importers/show.html.erb
=> fixed collection entries and added work entries to importer showpage

app/models/bulkrax/entry.rb, db/migrate/20191212155530_change_entry_last_error.rb
Very small change to make errors on entry easier to display to the user.
=> Serialize entry errors to json

app/controllers/bulkrax/importers_controller.rb, app/views/bulkrax/importers/show.html.erb, config/initializers/kaminari_config.rb
*Gif below only shows one item per page for demonstration purposes* The real config has 5 items per page.
=> i37 - added pagination for collection items on importer showpage

app/views/bulkrax/importers/show.html.erb
Removed "Row" column, display the number of results above pagination on the current page, changed format of the collection entries, and added the total number of works and collections to the metadata.
=> i50 - showpage improvements

app/factories/bulkrax/object_factory.rb
existing member_of_collection_ids need to be converted to collection objects
=> Object Factory collections bugfix

app/jobs/bulkrax/import_work_job.rb, app/models/bulkrax/csv_entry.rb, app/models/bulkrax/oai_entry.rb, app/parsers/bulkrax/bagit_parser.rb, app/parsers/bulkrax/csv_parser.rb, app/views/bulkrax/importers/show.html.erb, spec/controllers/bulkrax/importers_controller_spec.rb, spec/factories/bulkrax_importer_runs.rb, spec/jobs/bulkrax/child_relationships_job_spec.rb, spec/jobs/bulkrax/import_work_job_spec.rb, spec/models/bulkrax/csv_entry_spec.rb, spec/parsers/bulkrax/csv_parser_spec.rb
* handle spaces in filenames (affects CSV Import)
* fix importer show page error where raw_metadata is nil (affects OAIEntry)
* make tests pass
=> Handle spaces in filenames, and other fixes

app/factories/bulkrax/object_factory.rb, app/jobs/bulkrax/import_work_job.rb, app/models/concerns/bulkrax/import_behavior.rb
* destroy_existing_files nowbeing called on replace_files == true
* use object, rather than @object apart from when we're setting @object
* re-raise the CollectionsCreatedError
=> Small fixes to object factory

db/migrate/20191212155530_change_entry_last_error.rb
I have found that the original migration is unreliable, so I've rewritten it with raw SQL.
=> Rewrite the migration for entry last_error

app/models/bulkrax/exporter_run.rb, app/views/bulkrax/exporters/index.html.erb
=> i58 exporter index page

lib/generators/bulkrax/install_generator.rb
concerns/bulkrax rather than bulkrax/concerns
=> Correct path in install generator

app/assets/stylesheets/bulkrax/application.css, app/controllers/bulkrax/exporters_controller.rb, app/controllers/bulkrax/importers_controller.rb, app/models/bulkrax/importer.rb, app/models/concerns/bulkrax/download_behavior.rb, app/parsers/bulkrax/csv_parser.rb, app/views/bulkrax/importers/show.html.erb, config/routes.rb, spec/controllers/bulkrax/importers_controller_spec.rb, spec/factories/bulkrax_entries.rb, spec/factories/bulkrax_importers.rb, spec/fixtures/csv/failed.csv, spec/parsers/bulkrax/csv_parser_spec.rb, spec/rails_helper.rb
=> i49 Export Errored Entries

app/assets/stylesheets/bulkrax/application.css, app/controllers/bulkrax/importers_controller.rb, app/views/bulkrax/importers/show.html.erb, app/views/bulkrax/importers/upload_corrected_entries.html.erb, config/routes.rb, spec/controllers/bulkrax/importers_controller_spec.rb
=> i52 Upload Corrected CSV Entries view

db/migrate/20190731114016_change_importer_and_exporter_to_polymorphic.rb
Refactors the polymorphic migration to rename_column rather than add / remove
=> Fix migration errors

app/matchers/bulkrax/application_matcher.rb, app/views/bulkrax/importers/show.html.erb
Nils in CSV files were throwing an error. They should simply be the same as ""
=> Blanks in csv

app/views/bulkrax/importers/show.html.erb
Importer show was throwing an exception because field_mapping was nil
=> Fix importer show

app/controllers/bulkrax/importers_controller.rb, app/controllers/concerns/bulkrax/api.rb, app/helpers/bulkrax/validation_helper.rb, app/matchers/bulkrax/application_matcher.rb, app/models/bulkrax/importer.rb, app/parsers/bulkrax/csv_parser.rb, app/views/bulkrax/importers/_form.html.erb, lib/bulkrax.rb, lib/generators/bulkrax/install_generator.rb, lib/generators/bulkrax/templates/bin/importer, lib/generators/bulkrax/templates/config/bulkrax_api.yml, spec/controllers/bulkrax/importers_controller_spec.rb, spec/lib/bulkrax_spec.rb, spec/parsers/bulkrax/csv_parser_spec.rb, spec/rails_helper.rb, spec/test_app/app/models/user.rb, spec/test_app/config/bulkrax_api.yml
This PR:
* adds a JSON api to the importers for create / update / delete
* adds a CLI to create / update an importer via the JSON API
* uses Token authentication for JSON API
* adds documentation to the [wiki](https://github.com/samvera-labs/bulkrax/wiki)
TODO - add more tests
=> JSON API and CLI

Gemfile.lock, bulkrax.gemspec
Updated gem, ran tests (existing failures are unrelated and fixed in i53)
=> Upgrade oai to v1

spec/test_app/db/schema.rb
Result of running migrations on latest master
=> update db schema for test_app

app/models/bulkrax/xml_entry.rb, app/models/concerns/bulkrax/has_matchers.rb, app/parsers/bulkrax/xml_parser.rb, lib/bulkrax.rb, spec/factories/bulkrax_importers.rb, spec/fixtures/xml/good.xml, spec/fixtures/xml/single.xml, spec/lib/bulkrax_spec.rb, spec/models/bulkrax/xml_entry_spec.rb, spec/parsers/bulkrax/xml_parser_spec.rb
=> XML Importer - specs

app/controllers/bulkrax/importers_controller.rb
yes "strong_paramy" is a word ;-)
=> exclude the file and selected_files params in a more strong_paramy way

app/controllers/bulkrax/importers_controller.rb
@orangewolf ... this is working for me on file_system, not tried on cloud proper
=> Fix cloud_params?

app/controllers/bulkrax/importers_controller.rb, app/models/bulkrax/csv_entry.rb, app/models/bulkrax/importer.rb, app/parsers/bulkrax/csv_parser.rb, spec/models/bulkrax/importer_spec.rb
I'm pretty sure this is the right direction on these. Doctor Julie can I get a consult?
=> we now detect parsed fields, so these need to be swapped

.github/workflows/rubocop.yml
run rubocop on push to master, rename job
=> Run Rubocop Workflow on push to master

app/jobs/bulkrax/child_relationships_job.rb, spec/jobs/bulkrax/child_relationships_job_spec.rb
ended up doing some refactoring to find the bug
=> was having issues with relating works to each other

app/controllers/bulkrax/exporters_controller.rb, app/controllers/bulkrax/importers_controller.rb, spec/test_app/config/initializers/hyrax.rb
Bonus: less words to describe the same thing!
Related to https://github.com/samvera/hyrax/commit/ad5e64590f91a8fdf2c3ff812b278ba73eee487e
=> Reworking wording away from "white list"

app/models/bulkrax/csv_entry.rb, app/models/bulkrax/exporter.rb, app/parsers/bulkrax/application_parser.rb, spec/rails_helper.rb
specifically around running the same exporter twice and complex data fields
=> fix errors seen when running through real world exports

app/models/bulkrax/exporter.rb, app/models/bulkrax/exporter_run.rb, app/models/bulkrax/importer.rb, app/models/bulkrax/importer_run.rb, app/views/bulkrax/exporters/index.html.erb, app/views/bulkrax/importers/index.html.erb
importer and export status's not displaying or showing failed even if 99% of records processed.
=> consolidate and clean up status issues

app/controllers/bulkrax/application_controller.rb, app/helpers/bulkrax/application_helper.rb, app/views/bulkrax/shared/_bulkrax_errors.html.erb, app/views/bulkrax/shared/_bulkrax_field_mapping.html.erb
Fixes `uninitialized constant CodeRay` error on several views
=> Require CodeRay in application_controller so all views can access it

README.md, lib/generators/bulkrax/install_generator.rb
Add `require 'bulkrax/application'` to application.css in install generator and a note in README for manual installation
=> Add require to application.css in install generator

app/controllers/bulkrax/exporters_controller.rb, app/models/bulkrax/exporter.rb, app/parsers/bulkrax/csv_parser.rb, app/views/bulkrax/exporters/_form.html.erb, config/locales/bulkrax.en.yml, db/migrate/20201117220007_add_workflow_status_to_bulkrax_exporter.rb
Added the ability to filter via `workflow status` to exporters.
=> Added filter to export by workflow status

CONTRIBUTING.md
add instructions on how a contributor can run the specs
=> run the spec suite

app/views/hyrax/dashboard/sidebar/_bulkrax_sidebar_additions.html.erb, lib/bulkrax/engine.rb, lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
fixes issue where bulkrax link do not show in the sidebar in hyrax 3.x
=> importers and exporters links in hyrax 3.x

CONTRIBUTING.md
- add instructions on how to run rubocop on a single file
=> running rubocop

app/models/concerns/bulkrax/has_matchers.rb
- update the variable name of "object" to "object_name" so people better understand what it is
=> update references of "object" to "object_name"

app/matchers/bulkrax/application_matcher.rb, app/models/bulkrax/csv_entry.rb, app/models/concerns/bulkrax/has_matchers.rb, spec/models/bulkrax/csv_entry_spec.rb
https://github.com/samvera-labs/bulkrax/issues/296
- getting the index of an item based on the column header so mappings are always correct
- object keys that have an array as the value succeed
=> 296 object with nested values

app/helpers/bulkrax/application_helper.rb, app/jobs/bulkrax/import_work_job.rb, app/models/bulkrax/entry.rb, app/models/bulkrax/import_failed.rb, app/models/bulkrax/importer.rb, app/models/concerns/bulkrax/status_info.rb, app/parsers/bulkrax/application_parser.rb, app/parsers/bulkrax/bagit_parser.rb, app/parsers/bulkrax/csv_parser.rb, app/parsers/bulkrax/oai_dc_parser.rb, app/parsers/bulkrax/xml_parser.rb, app/views/bulkrax/entries/show.html.erb, app/views/bulkrax/shared/_bulkrax_errors.html.erb, spec/factories/bulkrax_importers.rb, spec/features/oai_dc_importer_spec.rb, spec/jobs/bulkrax/import_work_job_spec.rb, spec/parsers/bulkrax/bagit_parser_spec.rb
=> Work on invalid record status display, counter updates and use source_identifier_symbol in all parsers

app/models/bulkrax/exporter.rb, app/models/concerns/bulkrax/export_behavior.rb, lib/bulkrax/engine.rb, spec/test_app/config/application.rb
this can be removed after dummy app is upgraded to rails 5.2
Closes #279
=> rescue fixture replacement

app/models/bulkrax/csv_entry.rb
should export based on keys rather than from value (since that is the import source), also should export collection ids
=> Draft: should export collection ids and rights statements

.github/workflows/branches.yml, .github/workflows/lint.yml, .github/workflows/test.yml, CONTRIBUTING.md, README.md, app/helpers/bulkrax/importers_helper.rb, app/models/concerns/bulkrax/download_behavior.rb
- updates README Ref #292 
- updates CONTRIBUTING Ref #293 
- adds step to github ci to detect master #291 
After github changes, this PR should cover everything else in #290
=> Main rename code changes

Gemfile.lock, app/parsers/bulkrax/csv_parser.rb, lib/bulkrax/version.rb
fixes missing collections header in CSV. collection ids will not show in CSV's without this.
=> 73 rights and collections export

app/factories/bulkrax/object_factory.rb, app/models/bulkrax/csv_entry.rb, app/models/concerns/bulkrax/import_behavior.rb
same as one for update... somehow I missed this on the last PR
also checks for hashes being passed in rather than just id's and fixes this.
=> fixes hash having integers as keys on create

app/parsers/bulkrax/csv_parser.rb
Ref https://github.com/samvera-labs/bulkrax/issues/321<br>
Relies on https://gitlab.com/notch8/britishlibrary/-/merge_requests/152 
- exporting from an importer only exports works from the chosen importer
the first importer imported 1 article work type
the second importer imported 1 book work type
I exported from the "book" importer and didn't get the article work. 🎉 
[export 30.csv](https://github.com/samvera-labs/bulkrax/files/7126591/export.30.csv)
=> 321-export-from-importer

app/parsers/bulkrax/csv_parser.rb
co-author: <rob@notch8.com>
- object related headers are grouped together
- object related headers are in numerical order
[export_Book_from_worktype 7.csv](https://github.com/samvera-labs/bulkrax/files/7282801/export_Book_from_worktype.7.csv)
=> order-of-columns

app/models/concerns/bulkrax/import_behavior.rb
I kept getting "undefined method `method_defined?` for nil:NilClass" when importing a csv. I tracked the issue down to `def factory_class` in import_behvior.rb. 
- the correct value is returned for a collection or model factory class
=> returning-model-factory-class-again

app/models/concerns/bulkrax/import_behavior.rb
This commit was supposed to go in with #383 🤦
=> Use parsed relationship mappings in entry parsed_metadata

lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
=> add documentation for configuring relationship importing to generator

db/migrate/20190731114016_change_importer_and_exporter_to_polymorphic.rb
=> Fix Mysql Migration Issue

app/factories/bulkrax/object_factory.rb, app/jobs/bulkrax/create_relationships_job.rb, app/models/bulkrax/csv_entry.rb, app/models/bulkrax/entry.rb, app/models/bulkrax/oai_entry.rb, app/models/bulkrax/rdf_entry.rb, app/models/bulkrax/xml_entry.rb, app/models/concerns/bulkrax/has_matchers.rb, app/models/concerns/bulkrax/import_behavior.rb, app/parsers/bulkrax/application_parser.rb, app/parsers/bulkrax/bagit_parser.rb, app/parsers/bulkrax/csv_parser.rb, lib/bulkrax.rb, lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
Since 2.0 is being released soon, give users more time to upgrade
=> Update collection_field_mapping deprecation warnings

spec/test_app/db/schema.rb
Done by running `rails db:migrate ENV=test`
=> Restore test db schema

Gemfile.lock, lib/bulkrax/version.rb
- update bulkrax to v.3.0.0.beta4
=> update bulkrax to v.3.0.0.beta4

app/views/bulkrax/exporters/show.html.erb, app/views/bulkrax/importers/show.html.erb
=> remove collection column on the importer and exporter show page

app/views/bulkrax/exporters/show.html.erb, app/views/bulkrax/importers/show.html.erb
Added pending icon to import show page for fileset entries and exporter show page for work entries.
=> 3rd attempt to push branch for pending icon

app/views/bulkrax/exporters/_form.html.erb, config/locales/bulkrax.en.yml
Trying to get passed the clabot, will delete old branch
=> Generated metadata and thumbnails hint text 2

Gemfile.lock, app/factories/bulkrax/object_factory.rb, app/jobs/bulkrax/create_relationships_job.rb, app/models/concerns/bulkrax/dynamic_record_lookup.rb, lib/bulkrax/version.rb, spec/jobs/bulkrax/create_relationships_job_spec.rb, spec/models/concerns/bulkrax/dynamic_record_lookup_spec.rb
- include all of the beta5 updates in the branch that pals is currently using
=> Include v.3.0.0.beta5 updates

.github/workflows/test.yml, spec/jobs/bulkrax/importer_job_spec.rb
=> remove ruby 2.5 from testing as 2.5 is EOL

app/jobs/bulkrax/import_collection_job.rb, app/models/concerns/bulkrax/import_behavior.rb, app/parsers/bulkrax/csv_parser.rb, spec/jobs/bulkrax/importer_job_spec.rb
ref: https://github.com/samvera-labs/bulkrax/issues/495
Don't create permission template accesses for collections on validate only
authored by braydon j.
=> Don't create permission template accesses for collections on validate only

app/jobs/bulkrax/export_work_job.rb, app/models/bulkrax/exporter.rb, app/parsers/bulkrax/csv_parser.rb, spec/models/bulkrax/exporter_spec.rb, spec/parsers/bulkrax/csv_parser_spec.rb
Ref: https://gitlab.com/notch8/palni-palci/-/issues/468
Before: Although it says "Complete", it is actually not complete and that is why the download button is not there.
After:
| while pending | upon completion |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/19597776/169114909-c43e54d6-ac09-4fca-87e4-fff5920ee167.png) | ![image](https://user-images.githubusercontent.com/19597776/169115787-4f8c7c4d-39c6-4592-bf8a-438f0fd64f7d.png)|
=> Erroneous complete status

app/jobs/bulkrax/delete_collection_job.rb, app/jobs/bulkrax/delete_file_set_job.rb, app/jobs/bulkrax/delete_job.rb, app/parsers/bulkrax/csv_parser.rb, app/views/bulkrax/importers/show.html.erb
Add `DeleteCollectionJob` and `DeleteFileSetJob`
=> Allow deletion of Collections and FileSets via CSV import

app/jobs/bulkrax/importer_job.rb, app/models/bulkrax/importer.rb, spec/jobs/bulkrax/importer_job_spec.rb
Closes https://github.com/samvera-labs/bulkrax/issues/398 
Do not infinitely retry importer job when CSV is malformed
=> #398 Handle malformed CSV errors better

Gemfile.lock, lib/bulkrax/version.rb
=> minor-version-bump-3.5.0

app/models/bulkrax/entry.rb, app/parsers/bulkrax/application_parser.rb
=> 548 remove bagit_zip_file_size_check

Gemfile, Gemfile.lock
add pry to gemfile just so devs have the option and don't have to add it themselves every time
=> add pry to dev testing

app/jobs/bulkrax/import_file_set_job.rb, spec/jobs/bulkrax/import_file_set_job_spec.rb
ref #591 
- reschedule the ImportFileSetJob properly
- return the correct parent record from #find_parent_record
=> 591 fix the ImportFileSetJob

app/parsers/bulkrax/csv_parser.rb, spec/parsers/bulkrax/csv_parser_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb: creates a test highlighting the bug's behavior.
=> Bug Fix (Issue #614): Fix the `path_to_files` method.

spec/parsers/bulkrax/csv_parser_spec.rb
- fix the commented out part of the #write_partial_import_file spec in the csv parser file
=> TODO-fix-csv-parser-spec

CONTRIBUTING.md
- remove reference to the cla in the contributing doc
=> remove-reference-to-cla

CONTRIBUTING.md
=> update contributing.md while testing appending "i" to a branch name

app/jobs/bulkrax/import_work_job.rb
Instead of re-finding the ImporterRun, store that run in a local variable.  Also instead of relying on the opaque arg order, name the args and use those (instead of `arg[0]` and `arg[1]`).
=> Naming arguments and reducing duplication in import_work_job

app/parsers/bulkrax/application_parser.rb
Prior to this commit, we didn't have much in the way of inline documentation regarding the `Bulkrax::ApplicationParser`.
With this commit, I've added documentation based on my preliminary read through.
=> Adding inline documentation

app/services/bulkrax/remove_relationships_for_importer.rb, spec/services/bulkrax/remove_relationships_for_importer_spec.rb
See the inline documentation for details
Closes #661
=> Adding Bulkrax::RemoveRelationshipsForImporter

app/views/bulkrax/shared/_file_set_entries_tab.html.erb
Fix issue with path variable not being used, resulitn exports incorrctly linking to an import path
=> Fix issue with path variable not being used

app/models/concerns/bulkrax/import_behavior.rb
@no-reply what do you think about this change?  This is mainly for projects that have Bulkrax already set up and don't have/don't know about the generated config that update to the latest version of Bulkrax.  Also, this should fix specs.
=> fallback to default

lib/tasks/reset.rake
Ref #647
It is very useful to clear out data when one is testing importers.
=> add reset task for hyrax to bulkrax

app/models/bulkrax/oai_entry.rb
updates the collection lookup to be the same for both lookups in this method
=> change the way we lookup collection ids

app/views/bulkrax/exporters/_form.html.erb, app/views/bulkrax/exporters/edit.html.erb, app/views/bulkrax/exporters/new.html.erb, app/views/bulkrax/importers/_form.html.erb
- Adds bootstrap classes to forms
- Adds class to export form to match the class on the importer form
=> add bootstrap classes to forms

app/jobs/bulkrax/create_relationships_job.rb, app/models/bulkrax/importer_run.rb, app/models/bulkrax/pending_relationship.rb, app/models/concerns/bulkrax/dynamic_record_lookup.rb, lib/bulkrax.rb, spec/factories/bulkrax/pending_relationships.rb, spec/jobs/bulkrax/create_relationships_job_spec.rb, spec/models/bulkrax/importer_run_spec.rb
with a single run that never adds all the objects to memory
=> replace multiple times through the pending realtionship loop

app/jobs/bulkrax/create_relationships_job.rb
solves memory leak issue as reported by UTK
=> instrament realtionship job to solve memory leak

app/models/bulkrax/exporter.rb, app/models/bulkrax/importer.rb, app/models/bulkrax/pending_relationship.rb, app/models/concerns/bulkrax/export_behavior.rb, app/models/concerns/bulkrax/import_behavior.rb, app/parsers/bulkrax/application_parser.rb, app/parsers/bulkrax/bagit_parser.rb, app/parsers/bulkrax/csv_parser.rb, app/parsers/bulkrax/xml_parser.rb
=> Favoring non-deprecated method name

app/jobs/bulkrax/import_work_job.rb
> these [changes prior to 5c2c7954][1] were on purpose to prevent race
> conditions on the database update. If you do not re-find (or at least
> reload) the object on each increment, the count can get messed
> up. Let's say there are two jobs A and B and a counter set to 2.
>
> - A grabs the importer_run (line 10)
> - B grabs the importer_run (line 10)
> - A Finishes the build, does the increment (now the counter is 3)
> - B Finishes the build, does the increment (now the counter is 3 again)
>   and thus a count is lost.
Related to:
- https://github.com/samvera-labs/bulkrax/pull/653
[1]: https://github.com/samvera-labs/bulkrax/commit/5c2c795452e13a98c9217fdac81ae2f5aea031a0#r105848236
=> Fixing timing regression for incrementation

app/parsers/bulkrax/parser_export_record_set.rb
Prior to this commit, we were querying all of the candidate file set IDs for the associated work type.  In the case of the below exporter, we had 1196 IDs to query.
As we were testing if there was a query size limit, we noticed that we could query 1024 IDs but not 1025.  We add other query parameters, to bump the query size, but at 1024 IDs things worked.  At 1025 they failed.
Digging further, we saw that there is hard (yet configurable) limit for SOLR query OR clauses.  In our case, 1024.  (Hint: if you powers of 2, dig a little).
With this commit, we instead request 512 IDs at a time and join those results into a single array.
Note: there are other queries that will need similar fixing but for the time being, this (we hope) resolves a client urgency.
See: …
=> Addressing SOLR maxBooleanClauses for WorkType export

app/jobs/bulkrax/schedule_relationships_job.rb, app/models/bulkrax/csv_entry.rb, app/parsers/bulkrax/parser_export_record_set.rb, app/views/bulkrax/entries/show.html.erb, app/views/bulkrax/exporters/_form.html.erb, lib/bulkrax.rb, spec/lib/bulkrax_spec.rb
sets up exports for non hyrax systems.
=> Non hyrax exports

lib/bulkrax/version.rb
update version.rb to reflect v5.2.0
=> minor-version-bump-v5.2.0

app/parsers/bulkrax/csv_parser.rb, spec/fixtures/csv/all_record_types_whitespace.csv, spec/parsers/bulkrax/csv_parser_spec.rb
Fixes https://github.com/samvera-labs/bulkrax/issues/801
=> strip whitespace from model values so they get assigned correctly

app/parsers/bulkrax/parser_export_record_set.rb
This builds on the refactor of #808, which separated the in batches
concept from the query generation concept.
This should resolve the issue of attempting to export all of the records
that were imported via an importer when the number of imported records
exceeds the SOLR limit of `OR`-ed logic.
Closes #775
Related to:
- https://github.com/samvera-labs/bulkrax/issues/776
- https://github.com/scientist-softserv/britishlibrary/issues/373
- https://github.com/scientist-softserv/palni-palci/pull/440
- https://github.com/samvera-labs/bulkrax/issues/775
- https://github.com/samvera-labs/bulkrax/pull/808
=> 🐛 Adding in_batches handling of Importer based export

app/assets/javascripts/bulkrax/navtabs.js, app/assets/javascripts/bulkrax/navtabs.js.erb
This commit will wrap a conditional around navtabs.js to avoid erroring on Hyku applications.
=> 🐛 Modify navtabs.js

lib/bulkrax/version.rb
Following newly updated instructions at:  https://playbook-staging.notch8.com/en/samvera/bulkrax/release-a-new-version#set-the-version-number
=> 💸 Minting version 5.3.0

app/views/bulkrax/entries/show.html.erb, config/locales/bulkrax.en.yml
Trying to sync up with existing support for changing these labels in different views
=> Support additional view i18n labels

lib/bulkrax/version.rb
Mostly a small collection of bug fixes.
Ref:
- https://playbook-staging.notch8.com/en/samvera/bulkrax/release-a-new-version#set-the-version-number
=> 💸 Minor bump to v5.4.0

app/views/hyrax/dashboard/sidebar/_bulkrax_sidebar_additions.html.erb
not sure how this one got through CI
=> fix syntax error in ERB

spec/test_app/config/application.rb
This is a redo of #916 that doesn't depend on the new datatables. Not sure why I didn't just cherry pick it in the first place.
=> Need to Include dry/monads in sample app to get generators working

lib/tasks/bulkrax_tasks.rake
Fixes https://github.com/samvera/bulkrax/issues/941
=> Add require ruby-progressbar

db/migrate/20240307053156_add_index_to_metadata_bulkrax_identifier.rb
=> Downgraded ActiveRecord method version from 6.1 to 5.2 - Fixes #948

app/parsers/bulkrax/application_parser.rb
=> Typo in visibility values doc: embaro -> embargo

app/factories/bulkrax/valkyrie_object_factory.rb
Prior work to handle remote files did not work for local files.
Prior work: 
- https://github.com/samvera/bulkrax/pull/975
- https://github.com/samvera/bulkrax/pull/971
- https://github.com/samvera/bulkrax/pull/968
- https://github.com/samvera/bulkrax/pull/967
Refs:
- https://github.com/scientist-softserv/palni-palci/issues/1010
=> Importing local files broke due to remote files work

.github/workflows/test.yml, app/factories/bulkrax/object_factory.rb, app/jobs/bulkrax/delete_file_set_job.rb, spec/test_app/db/schema.rb
AF deletes should free up the id for reuse and file set deletes should only save the parent if the parent exists and is AF
=> ActiveFedora based deletion issues

Gemfile
use conditional logic to continue to support old hyrax for now
=> hyrax 5 is out but does not support ruby 2.7

lib/bulkrax/version.rb
=> minor version bump

lib/bulkrax/version.rb
=> Bumps to minor version v9.1.0

.github/workflows/test.yml, Gemfile, app/models/bulkrax/csv_entry.rb, app/models/bulkrax/entry.rb, app/models/bulkrax/exporter.rb, app/models/bulkrax/importer.rb, app/models/bulkrax/oai_entry.rb, app/models/bulkrax/rdf_entry.rb, app/models/bulkrax/status.rb, app/models/bulkrax/xml_entry.rb, bulkrax.gemspec, spec/rails_helper.rb, spec/test_app/config/application.rb
Fixes #1056 
Add support for Rails 7.2 and Hyrax 5.2
=> Fixes for Rails 7.2
