samvera/bulkrax

- app/matchers/bulkrax/oai_matcher.rb
There were a few duplicate conditions. While this didn't hurt functionality now, it could make things complicated later. These have been removed.
Also, minor cleanup.
> Remove duplicates in OAIMatcher#parse_format_digital

- spec/factories/collections.rb
- spec/features/oai_dc_importer_spec.rb
Fixes #6 - prevent Solr connection by adding a factory for collection and stubbing the call to Collection.where in `oai_dc_importer_spec`.
> Add a factory for collection and stub the call to Collection.where

- app/assets/javascripts/bulkrax/importers.js.erb
This PR fixes an issue where sets were not refreshing if the partial for the parser changes.
The cause was the variables `base_url` and `external_set_select` being created by the prepBulkrax event, but not being refreshed on change. The solution is to refresh the base_url on leaving the base_url field, and only creating the `external_set_select` when it is needed, rather than globally.
Another small issue was fixed whereby when the importers page loads, there is a javascript error thrown because `parser_klass.data('partial')` is null yet `.length` is being called on it.
> Fix issue where sets were not refreshing on change of partial.

- lib/bulkrax/engine.rb
With the latest change I'm getting `lib/bulkrax/engine.rb:7:in `match': wrong argument type true (expected Regexp) (TypeError)`
Wrapping the match input in brackets fixes it.
> Fix wrong argument type error with brackets

- app/models/bulkrax/concerns/has_local_processing.rb
- app/models/bulkrax/csv_collection_entry.rb
- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/entry.rb
- app/models/bulkrax/oai_entry.rb
- app/models/bulkrax/oai_set_entry.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/parsers/bulkrax/oai_dc_parser.rb
- app/views/bulkrax/importers/_oai_fields.html.erb
This PR removes ATLA specific code. An accompanying PR in ATLA will add the necessary code there.
It also:
* removes self.parser_fields from the parser - this doesn't appear to be used any more
* moves the identifier setting in the entry build to the top, I introduced a bug where the identifier was not being set (because of unnecessary cacheing).
> remove atla specific code

- app/models/bulkrax/oai_entry.rb
There was a bug in the logic of `Bulkrax::OaiEntry#collections_created?`. We were looking for sets.length to be the same as the length of collection_ids but if we are harvesting from only one set, but the record belongs to many in OAI, the logic breaks down. Instead, we should check for sets.length only when harvesting 'All', and otherwise look for one collection_id.
Whilst works can be in multiple collections, OAI entries should only have multiple collection_ids when running 'all'.
> Fixes a bug in collections_created?

- app/models/bulkrax/oai_entry.rb
- spec/models/bulkrax/oai_entry_spec.rb
There was still an issue with the logic, which should now be fixed:
* when a set is selected in the importer, ONE and only ONE collection is created, for that set
* entry.collection_ids will receive the identifier
* when 'all' is selected, a collection is created for ALL collections, if we can retrieve them from OAI for the record, in this case the entry.collection_ids will correspond to the number of sets
* when 'all' is selected, and we cannot retrieve sets from OAI for the record, no collections are created and entry.collection_ids will be 0
> Colletions created bugfix(2)

- app/factories/bulkrax/object_factory.rb
- app/jobs/bulkrax/import_work_job.rb
if a job does not build, it throws an exception during save, so it spawns jobs forever until there are millions of them.
> No more redudent jobs

- app/factories/bulkrax/object_factory.rb
- lib/bulkrax.rb
Remote files may not have :url set and would error out if they did not. this was actually the default for csv remote files, which I don't think actually uploaded?
> Fix remote files parsing

- app/matchers/bulkrax/application_matcher.rb
Hyrax::ResourceTypesService throws a KeyError when the id isn't matched.
The resource types parser should return nil if a KeyError is raised.
> Handle KeyError in Hyrax::ResourceTypesService

- Gemfile.lock
- app/matchers/bulkrax/application_matcher.rb
- app/models/bulkrax/entry.rb
- app/models/bulkrax/importer.rb
- app/models/bulkrax/oai_entry.rb
- app/parsers/bulkrax/csv_parser.rb
- app/parsers/bulkrax/oai_dc_parser.rb
- bulkrax.gemspec
- db/migrate/20190729124607_create_bulkrax_exporters.rb
- db/migrate/20190729134158_create_bulkrax_exporter_runs.rb
- db/migrate/20190731114016_change_importer_and_exporter_to_polymorphic.rb
- spec/factories/bulkrax_entries.rb
- spec/lib/bulkrax_spec.rb
- spec/models/bulkrax/csv_entry_spec.rb
- spec/models/bulkrax/entry_spec.rb
- spec/models/bulkrax/oai_entry_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
- spec/rails_helper.rb
- spec/test_app/db/schema.rb
This PR adds migrations and changes to models / parser to make way for the exporter work.
When the new migrations are run, they should update existing `Bulkrax::Entry objects`, moving the `importer_id` to `importerexporter_id` before removing the `importer_id` column.
In addition:
* fix `spec/lib/bulkrax.rb`
* fix `spec/models/bulkrax/csv_entry_spec.rb`
* remove simple_form dependency; allow rails 5.2.*
> Database and association changes for exporter

- app/models/bulkrax/entry.rb
- db/migrate/20190731114016_change_importer_and_exporter_to_polymorphic.rb
This PR removes the deprecatoin of `belongs_to: importer` from Bulkrax::Entry and adds it into the migration.
> Remove deprecation of belongs_to: importer

- app/controllers/bulkrax/importers_controller.rb
- lib/bulkrax.rb
- lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
- spec/lib/bulkrax_spec.rb
There was a hard coded value, that's been turned into a config.
> Add a server_name config for the oai headers

- app/models/concerns/bulkrax/has_matchers.rb
- app/parsers/bulkrax/csv_parser.rb
Newer versions of rails need `require 'csv'` in the CSV parser.
There is an issue where an incomplete mapping will omit unmapped (but valid) fields. The only time fields should be omitted is if they are explicitly declared as excluded or not supported by hyrax.
> Fixes for CSV Import

- app/factories/bulkrax/image_factory.rb
- app/jobs/bulkrax/import_work_job.rb
- app/jobs/bulkrax/importer_job.rb
- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/entry.rb
- app/models/bulkrax/importer.rb
- app/models/bulkrax/oai_entry.rb
- app/models/concerns/bulkrax/import_behavior.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- spec/factories/bulkrax_entries.rb
- spec/factories/bulkrax_importers.rb
- spec/factories/collections.rb
- spec/jobs/bulkrax/import_work_job_spec.rb
- spec/jobs/bulkrax/importer_job_spec.rb
- spec/models/bulkrax/csv_entry_spec.rb
- spec/models/bulkrax/entry_spec.rb
- spec/models/bulkrax/oai_entry_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
This PR:
* makes it explicit when a CSV won't import because of missing required fields - previously, this would silently fail with no error message. Now an error is raised and will be seen in sidekiq.
* adds a `#validate_import` method to the parser, which can be expanded on for the validation work. Here it is used to check for required fields in CSV.
* returns a sensible error message if Collection doesn't implement/index the sytem identifier field - previously a Solr error would be thrown which didn't easily identify the issue
* dries up the find_collection methods used by the entries
* sets the image application factory system identifier to be the Bulkrax system identifier (if different identifiers are supplied, we'll get duplicate records) - this will be removed in #77 
* refactors …
> Improvements to CSV Importer

- app/factories/bulkrax/object_factory.rb
- app/jobs/bulkrax/child_relationships_job.rb
Small bugfix to fix two issues:
* use members= and not member_ids= for collections - the latter is not settable
* fix typo in ChildRelationshipsJob
> Use members= and not member_ids= in ObjectFactory

- app/models/bulkrax/csv_entry.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- Validates that files in the CSV exist at the assumed path (sub-directory called files).
- Adds this validation to parser#validate_import
- Adds similar validation to the Bagit parser
> File path validation

- app/jobs/bulkrax/import_work_job.rb
- app/models/concerns/bulkrax/import_behavior.rb
- db/migrate/20191212155530_change_entry_last_error.rb
Don't swallow RSolr::Error::Http - it's likely network related and we want to retry
> Re-try on RSolr::Error::Http

- app/assets/javascripts/bulkrax/importers.js.erb
- app/controllers/bulkrax/importers_controller.rb
- app/jobs/bulkrax/download_cloud_file_job.rb
- app/jobs/bulkrax/importer_job.rb
- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/importer.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/views/bulkrax/importers/_bagit_fields.html.erb
- app/views/bulkrax/importers/_browse_everything.html.erb
- app/views/bulkrax/importers/_csv_fields.html.erb
- app/views/bulkrax/importers/edit.html.erb
- spec/controllers/bulkrax/importers_controller_spec.rb
- spec/test_app/db/schema.rb
Adds Browse Everything for file system (mount) and cloud file upload.
Features:
* For CSV, used only for the files, not the CSV itself, and so separate to to the file upload toggle
* For BagIt, as option alongside the others
* Selected files are listed, and the button turns green
Issues:
* perform_now in download job will not work for large uploads - needs a mechanism from stopping the importer from running until all downloads are done
* it is not clear how to get the directory structure of an upload, therefore we need to accept only zipped files for BagIt
For Bagit - one upload / file path only
> I17 browse everything

- app/parsers/bulkrax/csv_parser.rb
Fixes the logic of `CSV#file_paths` to ensure it returns an Array.
> CSV#file_paths was returning a String

- app/controllers/bulkrax/importers_controller.rb
We've had problems in Atla where the thumbnail were initially wrong and a re-run doesn't seem to fix it, because it's appending a second fileset, but the original 'broken' one is still set as the representative. By having a full re-harvest support replace, we will get rid of the old file_sets.
> Replace files for an OAI re-harvest of all items

- app/models/bulkrax/entry.rb
`valid_system_id` should only raise an error if the class *doesn't* support the property.
> Fixes bug in valid_system_id where logic was reversed

- app/models/bulkrax/csv_entry.rb
Fixes a bug where the matcher_class method on CSVEntry should be a class method.
> matcher_class should be a class method

- app/models/bulkrax/entry.rb
- app/models/concerns/bulkrax/has_matchers.rb
- app/parsers/bulkrax/bagit_parser.rb
- lib/generators/bulkrax/templates/app/models/concerns/bulkrax/has_local_processing.rb
- spec/models/bulkrax/entry_spec.rb
This PR fixes #86 whereby bulkrax assumes all properties are multi-valued and therefore the factory.run will fail if there are arrays supplied for singular properties.
Now we check the property and act accordingly in building the parsed_metadata.
Also includes a fix for the generator, which was putting the has_local_processing in the wrong place.
> Singular properties

- .rubocop.yml
- db/migrate/20191212155530_change_entry_last_error.rb
- spec/test_app/db/schema.rb
**This PR contains two changes:** 
1. Fixed a migration 
Was encountering a `TypeError: superclass mismatch for class Entry` when running the migrations against the test database. Judging by the fix, this appeared to be a scoping problem. 
2. Tweaked the rubocop config 
Rubocop's auto-fix command added a magic comment to the top of the test_app's database schema, but when the migrations are run against the test database, the comment gets removed automatically. So we'll just remove the comment and ignore the rule for that one  file.
> fix change_entry_last_error migration, tweak rubocop config

- app/jobs/bulkrax/export_work_job.rb
- app/jobs/bulkrax/import_work_collection_job.rb
- app/models/bulkrax/exporter.rb
- app/models/bulkrax/importer.rb
- app/models/concerns/bulkrax/importer_exporter_behavior.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/parsers/bulkrax/oai_dc_parser.rb
- app/views/bulkrax/importers/index.html.erb
- spec/fixtures/csv/good.csv
- spec/jobs/bulkrax/export_work_job_spec.rb
- spec/jobs/bulkrax/importer_job_spec.rb
- spec/models/bulkrax/importer_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
This PR does the following ensures that both collections and works are counted in the enqueued, processed and failed columns. It also adds the total collections to the `current_importer_run.create!` call and streamlines `increment_counters`.
> Importer index page counters improvements

- app/parsers/bulkrax/csv_parser.rb
- spec/factories/bulkrax_entries.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
Ignore entries with type `Bulkrax::CsvCollectionEntry` in `Bulkrax::CsvParser#write_errored_entries_file` 
Addendum to #125
> ignore Collection entries in errored_entries flow

- app/parsers/bulkrax/application_parser.rb
Refactor `ApplicationParser#find_or_create_entry` to avoid using the raw_metadata in the where clause.
> Fix find_or_create

- app/views/bulkrax/entries/show.html.erb
Affects OAI entries particularly as we don't store raw_metadata on those.
> Deal with blank raw_metadata on entry

- .gitignore
- app/controllers/bulkrax/importers_controller.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/views/bulkrax/importers/upload_corrected_entries.html.erb
- spec/controllers/bulkrax/importers_controller_spec.rb
- spec/jobs/bulkrax/exporter_job_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
- spec/rails_helper.rb
Implements the logic behind processing uploaded corrected CSV entries.
https://github.com/samvera-labs/bulkrax/pull/133
- The entries will be matched with those in the original importer (ie. a new importer will not be created) and updated. 
- The user will be taken to the original importer page, where, if successful, no errors will now be listed. If there are still errors, they can export-correct-upload again.
- When a successful job works, it will wipe out the `last_error` field. 
_In second image, highlighted Entry was successfully corrected and thus had its status updated and its errors cleared._ 
Uploading corrected entries breaks Entry counters on Importer show and index pages. This side effect is captured here: https://github.com/samvera-labs/bulkrax/issues/144
> i43 upload corrected entries - processing

- app/controllers/bulkrax/application_controller.rb
Currently we do not inherit anything from the main apps ApplicationController. This makes injecting things like auth hard.  By just changing ActiveController::Base to ::ApplicationController (note the double colons) we can include before actions and other helpful items from the parent Rails app.
> fix controller inheritance to make multitenant work in hyku

- app/matchers/bulkrax/application_matcher.rb
- app/views/bulkrax/importers/show.html.erb
Sorry about the daily double
1) If a csv entry is empty (no quotes) it was failing on the split. This just to_s the nil
2) importer mapping method now wraps the field_mapping variable. this updates the show view to reflect that.
> Resolve crash on blanks in CSV files, issue with importer show

- spec/controllers/bulkrax/importers_controller_spec.rb
Resolves 
```ruby
Failure/Error: let(:controller) { subject }
SystemStackError:
stack level too deep
```
> avoid infinite loop in spec

- .gitignore
- app/controllers/bulkrax/importers_controller.rb
- app/jobs/bulkrax/importer_job.rb
- app/models/concerns/bulkrax/import_behavior.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/parsers/bulkrax/oai_dc_parser.rb
- app/views/bulkrax/entries/show.html.erb
- app/views/bulkrax/importers/new.html.erb
- app/views/bulkrax/importers/show.html.erb
- config/routes.rb
- db/migrate/20200108194557_add_validate_only_to_bulkrax_importers.rb
- spec/controllers/bulkrax/importers_controller_spec.rb
- spec/models/bulkrax/rdf_entry_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
- spec/test_app/db/schema.rb
Add a 'Create and Validate' feature that validates the importer before importing the data. 
This now:
* creates the importer and entries but not the works themselves
* offers discard and continue, discard deletes the importer and entries, discard re-runs it with work creation re-enabled
It is light on specs. I've added basic specs to the controller.
> Create and Validate

- app/assets/javascripts/bulkrax/entries.js
- app/assets/javascripts/bulkrax/importers.js.erb
- app/jobs/bulkrax/download_cloud_file_job.rb
- app/jobs/bulkrax/export_work_job.rb
- app/models/bulkrax/entry.rb
- app/models/bulkrax/importer.rb
- app/models/concerns/bulkrax/status.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/views/bulkrax/entries/show.html.erb
- app/views/bulkrax/importers/_bagit_fields.html.erb
- app/views/bulkrax/importers/_csv_fields.html.erb
- app/views/bulkrax/importers/_oai_fields.html.erb
- app/views/bulkrax/importers/index.html.erb
- app/views/bulkrax/importers/show.html.erb
- db/migrate/20200301232856_add_status_to_importers.rb
- spec/parsers/bulkrax/bagit_parser_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
- spec/test_app/db/schema.rb
This PR:
* adds last_error, last_error_at, last_succeeded_at to the importers table
* captures and stores errors in the same way as entries
* displays errors in the importer show
* displays failed on the importer index if the importer itself has failed
Also
* checks the 'file on server' box on edit (as this will always be true for edit)
* removes requirement for rights_statement
> Add last_error to importer

- bulkrax.gemspec
OAI 1.0 and OAI 0.4 are functionally equivalent in our use of them, though there is a warning that gets cleared. However blacklight-oai-provider 6.x depends on OAI 0.4. The updated blacklight-oai-provider requires updated blacklight, which doesn't work for Hyrax yet. Therefor, lets be permissive here on OAI versions until things can all be brought forward.
> Loosen up oai dependecy as blacklight-oai conflicts

- app/models/bulkrax/csv_entry.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- spec/models/bulkrax/rdf_entry_spec.rb
This PR:
* renames csv_parser#files_path as the name is too similar to other methods
* renames csv_entry#file_path to match
* adds comments
* refactors the new path_to_files method to use File.dirname
* fixes 2 broken tests
> Refactor and rename csv_parser#files_path

- app/views/bulkrax/importers/_bagit_fields.html.erb
- app/views/bulkrax/importers/_csv_fields.html.erb
- app/views/bulkrax/importers/_oai_fields.html.erb
- app/views/bulkrax/importers/_xml_fields.html.erb
This PR adds a visiblity option to all parser views, set to open/public by default to mirror existing default behaviour.
The base work for this was done for the xml importer, this PR rolls the behaviour to the other views.
> Add visiblity to all standard views

- app/controllers/bulkrax/importers_controller.rb
- app/models/bulkrax/csv_entry.rb
- app/parsers/bulkrax/csv_parser.rb
- Move params to correct location and allow values to be plucked out safely
- Map auth_header to headers, which is where the BrowseEverything retriever expects to find it
- Try to deal with CSV entry when someone maps something to file besides the column header "file"
> Various browse everything fixes

- app/models/concerns/bulkrax/has_matchers.rb
if a field is singular and unmatched and the value is nil, bulkrax throws an exception. This fixes that nil error
> Single unmatched nil error

- app/views/bulkrax/exporters/index.html.erb
- app/views/bulkrax/importers/index.html.erb
Adds the following features to the Importer and Exporter index tables: 
- Limit 
- Search 
- Pagination 
- Sorting (by column) 
As well as customizes the `language` used in the table to avoid confusion (by default, `DataTable` refers to rows as 'entries', which is its own concept in Bulkrax).
> Functional jQuery DataTables on Importer and Exporter index views

- app/controllers/bulkrax/entries_controller.rb
- app/controllers/bulkrax/exporters_controller.rb
- app/controllers/bulkrax/importers_controller.rb
- app/models/bulkrax/exporter.rb
- app/views/bulkrax/entries/show.html.erb
- app/views/bulkrax/exporters/edit.html.erb
- app/views/bulkrax/exporters/index.html.erb
- app/views/bulkrax/exporters/new.html.erb
- app/views/bulkrax/exporters/show.html.erb
- app/views/bulkrax/importers/edit.html.erb
- app/views/bulkrax/importers/new.html.erb
- app/views/bulkrax/importers/show.html.erb
- config/locales/bulkrax.en.yml
- config/routes.rb
- db/migrate/20200326235838_add_status_to_exporters.rb
- spec/test_app/db/schema.rb
Update the exporter show page in line with the importer show page (but without the Collections section).
> Exporter show page

- app/assets/javascripts/bulkrax/bulkrax.js
- app/assets/javascripts/bulkrax/importers.js.erb
- app/models/bulkrax/csv_entry.rb
- app/models/concerns/bulkrax/export_behavior.rb
- app/views/bulkrax/entries/show.html.erb
- app/views/bulkrax/exporters/show.html.erb
- app/views/bulkrax/importers/show.html.erb
- rename `ExportBehavior#work` to `#hyrax_record` for clarity 
- exported `Collections` no longer break `Entry` show view 
- standardize Toggle buttons 
- create new "global" JS file (before, the only reason the exporter views were working was because of javascript in the `importers.js.erb` file)
> Exporter show page - fixes

- app/parsers/bulkrax/application_parser.rb
Incorrect code, should have been 'basename' rather than 'dirname' ... the method is getting the filename without extension as this is where the zip will have been unzipped to.
> Fixes a bug in application_parser

- app/parsers/bulkrax/csv_parser.rb
When exporting from an import, look for the importer entry_class, as this might be different to the importer entry_class.
> Exporter entry_class fix

- app/assets/javascripts/bulkrax/application.js
Removed the jQuery and Boostrap sprockets includes from application.js file. It was causing javascript errors in my application
> Remove jquery and boostrap sprockets from javascript

- app/views/bulkrax/importers/_oai_fields.html.erb
I was seeing a warning in the logs that there were 2 "required" keys here
> Remove extra required attribute from oai form input field

- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/oai_entry.rb
- app/models/bulkrax/rdf_entry.rb
- app/models/bulkrax/xml_entry.rb
- app/models/concerns/bulkrax/import_behavior.rb
- spec/models/bulkrax/csv_entry_spec.rb
- spec/models/bulkrax/oai_entry_spec.rb
- spec/models/bulkrax/rdf_entry_spec.rb
- spec/models/bulkrax/xml_entry_spec.rb
Currently, it seems that bulkrax defaults to the default admin set for imported works, ignoring the admin set selected in the form.  I added a method to add the admin set id to the parsed metadata for importers and added tests to verify that the admin set id is captured.  I believe this is related to #216
> Add admin_set_id to parsed_metadata

- app/jobs/bulkrax/importer_job.rb
- app/models/bulkrax/importer.rb
- spec/jobs/bulkrax/importer_job_spec.rb
Possibly related to #234 ?
When we were testing the csv importer locally, we noticed that the corrected entries function did not seem to be working.  After downloading the failed records, updating the records, and reuploading the csv, the records still failed with the original error messages.  After looking a little more closely, it appears that the records are being parsed during the validation step in the importer job (https://github.com/samvera-labs/bulkrax/blob/master/app/jobs/bulkrax/importer_job.rb#L15) without first setting the only_updates importer attribute.  Since the records are only parsed once (https://github.com/samvera-labs/bulkrax/blob/master/app/parsers/bulkrax/csv_parser.rb#L27), the corrected entries are never used.  I added a line in the importer job to set the …
> Fix corrected entries functionality

- app/parsers/bulkrax/csv_parser.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
We have noticed that collection and work type exports seemed to be limited to 10 even with a form limit of 0 or blank. The ActiveFedora::SolrService.query method uses the solr default limit of 10 unless the rows parameter is used, so I added a rows parameter with a value close to the maximum allowed integer value.
> Add row param to solr queries for exports

- app/controllers/bulkrax/exporters_controller.rb
- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/exporter.rb
- app/parsers/bulkrax/csv_parser.rb
- app/views/bulkrax/exporters/_form.html.erb
- config/locales/bulkrax.en.yml
- db/migrate/20201106014204_add_date_filter_and_status_to_bulkrax_exporters.rb
- spec/jobs/bulkrax/exporter_job_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
allows for exporting within a date range, and visibility (status)
> Export from date range

- app/parsers/bulkrax/xml_parser.rb
- db/migrate/20201106014204_add_date_filter_and_status_to_bulkrax_exporters.rb
- db/migrate/20201117220007_add_workflow_status_to_bulkrax_exporter.rb
Running migrations are throwing errors: 
```sh
PG::DuplicateColumn: ERROR:  column "start_date" of relation "bulkrax_exporters" already exists
: ALTER TABLE "bulkrax_exporters" ADD "start_date" date excluded from capture: DSN not set
```
Guard to prevent these errors.
> Add guards to new migrations

- app/jobs/bulkrax/import_work_collection_job.rb
When creating a Collection through the UI, the creator is automatically assigned to the new Collection as a manager through the Collection's PermissionTemplate.
Currently, it seems like imported Collections don't get a PermissionTemplate.
We should create a PermissionTemplate for the imported Collection if one doesn't already exist and add the User who created the Importer as a manager of that Collection.
Resolves #244
> Imported Collections get a PermissionTemplate with a manager

- app/parsers/bulkrax/csv_parser.rb
In the case where a zip file is being imported, total was counting the lines in the zip file, not the contained .csv file.
> Correctly calculate totals for zipped csv imports

- app/parsers/bulkrax/csv_parser.rb
Use the field mapping for `:file` in `CsvParser#file_paths`. If `:file` has been mapped to a different import column name, `#file_paths` always returns an empty array.
There are almost certainly more places where fields are referenced directly instead of using the field mapping.
> Use mapping for :file in CsvParser#file_paths

- app/models/bulkrax/importer.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
Especially important in multi-tenant, but also relevant if db is reset
> make sure different versions of an importer with the same id do not cross-contaminate

- app/models/bulkrax/csv_entry.rb
- spec/models/bulkrax/csv_entry_spec.rb
for example title_1, title_2, title_3 all get parsed as title. The same is true with 1_title, 2_title (but not red_title, blue_title)
coauthor: <alisha@notch8.com>,<sara@notch8.com>
> Support csv headers with #_value or value_#

- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/parsers/bulkrax/oai_dc_parser.rb
- app/parsers/bulkrax/xml_parser.rb
- lib/bulkrax.rb
- lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
Adds a new setting to fill in missing source identifiers. The config option takes. a proc, which it will then call in context. Added examples of usage and a warning about duplicates.
> ability to fill in missing identifiers during import

- app/models/bulkrax/entry.rb
- app/models/bulkrax/exporter.rb
- app/models/bulkrax/importer.rb
- app/models/bulkrax/status.rb
- app/models/concerns/bulkrax/errored_entries.rb
- app/models/concerns/bulkrax/status_info.rb
- app/parsers/bulkrax/csv_parser.rb
- db/migrate/20210806044408_remove_unused_last_error.rb
- db/migrate/20210806065737_increase_text_sizes.rb
- spec/factories/bulkrax/statuses.rb
- spec/factories/bulkrax_entries.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
- spec/test_app/db/schema.rb
- We stopped writing last error in order to use the statuses table. There were still some places in the code that used it (and would never pass). @sephirothkod one of these was the "export the errors" for csv parsers.
- We use serialized text fields for storing error backtraces and field sets. These values were potentially too small for some use cases.
Closes #303
> Remove last_error, up database text field size

- app/models/bulkrax/csv_entry.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/parsers/bulkrax/oai_dc_parser.rb
- lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
- this code was duplicated several places it wasn't used
- needed to expand the fill in to better deal with the way Ruby does binding.
> Required element fixes

- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/csv_parser.rb
the csv parser calls field_supported which it does not define.
> CSV Parser Exporter Broken

- app/factories/bulkrax/object_factory.rb
- app/jobs/bulkrax/child_relationships_job.rb
- app/models/concerns/bulkrax/import_behavior.rb
- spec/jobs/bulkrax/child_relationships_job_spec.rb
found a couple instances in OD where these were subtly misaligned after recent work. seems like something that's likely to break a lot
> clean up object factory to use named args

- app/models/bulkrax/csv_entry.rb
- spec/models/bulkrax/csv_entry_spec.rb
Ref https://github.com/samvera-labs/bulkrax/issues/321
- bulkrax can export properties from a single object to a csv where the header has the object name prefixed
- bulkrax can export properties from a single object to a csv where the header does not have the object name prefixed
> 321 export single object fields

- app/matchers/bulkrax/application_matcher.rb
- app/models/bulkrax/importer.rb
- app/models/concerns/bulkrax/file_factory.rb
- app/models/concerns/bulkrax/has_matchers.rb
Hyrax changed how remote file names are handled. they have to be passed in to be valid now.
> make sure remote files get file_name set, or Hyrax after 2.5 will fail

- app/models/bulkrax/csv_entry.rb
- app/parsers/bulkrax/csv_parser.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
https://github.com/samvera-labs/bulkrax/pull/334
https://github.com/samvera-labs/bulkrax/pull/339
- the object headers were not being exported in https://github.com/samvera-labs/bulkrax/pull/339
- object headers are exported again
[export.csv](https://github.com/samvera-labs/bulkrax/files/7123162/export.csv)
> include object headers again

- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/entry.rb
- app/models/concerns/bulkrax/importer_exporter_behavior.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- spec/models/bulkrax/csv_entry_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
CSV export was using the wrong headers. If you specify `"title" => {from: ['display_title']}` in the mapper,
then you would expect the export to say `display_title` and not `title`. This was not the case.
This commit also adds a new option for the field mapping - join. The default behavior on export has been to
join fields together, but field_1,field_2 easier for users to edit. This will be the new default and join allows
you to specify the old behavior.
Also cleaned up object code on exporter and reduced cyclomatic complexity on some methods in csv entry.
> Refactor csv export to use from values instead of to values.

- app/jobs/bulkrax/importer_job.rb
- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/importer.rb
- app/models/concerns/bulkrax/importer_exporter_behavior.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- spec/jobs/bulkrax/importer_job_spec.rb
- spec/models/bulkrax/importer_spec.rb
Only extract zip files once, instead of attempting to extract them for every Entry created
> Fix file paths for Zip CSV imports 

- app/parsers/bulkrax/csv_parser.rb
- app/views/bulkrax/importers/index.html.erb
- spec/parsers/bulkrax/csv_parser_spec.rb
Ref https://github.com/samvera-labs/bulkrax/issues/351
- the amount of works in a csv comes back correct, despite line breaks, etc. in the data
check the "total works" label
| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/133532553-f8816907-5439-480f-ae52-4381c7470d05.png) | ![image](https://user-images.githubusercontent.com/29032869/133531103-52122b01-aebc-4266-b436-16b287de3a80.png)|
> 351-total-works-count

- app/parsers/bulkrax/csv_parser.rb
Ref https://github.com/samvera-labs/bulkrax/issues/357
- the exported csv will now include the source and "from" in the file name
- when exporting from a work type, it uses the model name as the source
- when exporting from a collection, it uses the collection id as the source
- when exporting from an importer, it used the importer id as the source
[export_Book_from_worktype.csv](https://github.com/samvera-labs/bulkrax/files/7200338/export_Book_from_worktype.csv)
[export_dae980bd-d332-4235-9d82-390b4f3e36e5_from_collection.csv](https://github.com/samvera-labs/bulkrax/files/7200359/export_dae980bd-d332-4235-9d82-390b4f3e36e5_from_collection.csv)
[export_2_from_importer.csv](https://github.com/samvera-labs/bulkrax/files/7200364/export_2_from_importer.csv)
> 357-more-specific-export-file-name

- app/models/bulkrax/csv_entry.rb
- app/parsers/bulkrax/csv_parser.rb
Ref https://github.com/samvera-labs/bulkrax/issues/355
- object headings are grouped together by object, not the order of the mapping in initializers/bulkrax.rb
exported csv: [export.csv](https://github.com/samvera-labs/bulkrax/files/7200079/export.csv)
> 355-exported-group-headers

- app/jobs/bulkrax/importer_job.rb
for some reason, the "total works" count started returning 0 consistently for import and export
- total works should once again return the correct amount of works in that import or export run
| | importer | exporter |
| --- | --- | --- |
| after | ![Screen Shot 2021-09-22 at 11 22 49 PM](https://user-images.githubusercontent.com/29032869/134464567-447c0cef-572c-4b24-8940-0c46798bf971.png) | ![Screen Shot 2021-09-22 at 11 33 04 PM](https://user-images.githubusercontent.com/29032869/134464643-4e2b3876-eefe-45fa-92b0-deb366280716.png)| 
| before | ![Screen Shot 2021-09-22 at 11 03 20 PM](https://user-images.githubusercontent.com/29032869/134464540-29f69c84-cc14-4ef8-91a4-8ca3f04cc14f.png) | ![Screen Shot 2021-09-22 at 11 31 51 PM](https://user-images.githubusercontent.com/29032869/134464624-c …
> return-total-works

- app/models/bulkrax/csv_entry.rb
Ref https://gitlab.com/notch8/britishlibrary/-/issues/148
- although I have no idea why the object would be nil and could not duplicate this error locally, we're now checking to make sure the object exists before calling a method on it
- `NoMethodError - undefined method 'with_indifferent_access' for nil:NilClass` error was received on BL prod
> object-metadata-nil-check

- app/models/bulkrax/exporter.rb
- app/models/bulkrax/importer.rb
- app/parsers/bulkrax/application_parser.rb
- lib/bulkrax.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
- spec/rails_helper.rb
https://gitlab.com/notch8/britishlibrary/-/issues/148#note_686505543
- import and export paths will now have the tenant name for hyku apps
- imports a csv and a zip successfully
- exports a csv successfully
- previously imported csv's/zip still have a valid import path, but the csv/zip should be re-imported for consistency and to avoid future issues
- previously exported csv's don't have a valid download anymore so they need to be re-exported
| csv import | zip import | export|
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/134754583-062d28e2-0aeb-4298-8b70-8214c76262a8.png) | ![image](https://user-images.githubusercontent.com/29032869/134754596-d96d1996-a974-4348-bead-a0cec9e2ee0a.png) |  ![image](https://user-images.githubusercontent.com/29032869/134754 …
> seperate-paths-by-tenant

- .rubocop_todo.yml
- app/factories/bulkrax/object_factory.rb
- app/jobs/bulkrax/child_relationships_job.rb
- app/jobs/bulkrax/import_collection_job.rb
- app/jobs/bulkrax/import_work_collection_job.rb
- app/jobs/bulkrax/importer_job.rb
- app/models/bulkrax/csv_collection_entry.rb
- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/importer.rb
- app/models/concerns/bulkrax/has_matchers.rb
- app/models/concerns/bulkrax/import_behavior.rb
- app/models/concerns/bulkrax/importer_exporter_behavior.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/parsers/bulkrax/oai_dc_parser.rb
- app/parsers/bulkrax/xml_parser.rb
- spec/fixtures/csv/collections.csv
- spec/fixtures/csv/mixed_works_and_collections.csv
- spec/jobs/bulkrax/child_relationships_job_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
- spec/parsers/bulkrax/xml_parser_spec.rb
Add ability to import collections with metadata when `:model` or model mappings are set to Collection **(CSV only)** 
| model | source_identifier | title | description |
| --- | --- | --- | --- |
| Collection | collection_1 | First Collection | Lorem ipsum |
Retains ability to import Collections by title when importing works 
| model | source_identifier | title | collection |
| --- | --- | --- | --- |
| Work | work_1 | First Work | Parent Collection |
> Add ability to import Collections with metadata

- app/factories/bulkrax/object_factory.rb
- app/matchers/bulkrax/application_matcher.rb
- app/models/concerns/bulkrax/has_matchers.rb
- app/parsers/bulkrax/csv_parser.rb
**https://github.com/samvera-labs/bulkrax/pull/373 must be merged first or we'll have the same problem that's fixed there.**
Ref: https://gitlab.com/notch8/britishlibrary/-/issues/185
- on import, all cell values (empty or filled in) are accounted for
- if a user would like to delete data on an import, remove the value from the cell under the appropriate header in the csv, and it will be removed from the metadata for that work
- metadata and files can be removed this way
| | csv's | before | after |
| --- | --- | --- | --- |
| metadata only | with all values: [185_bc.csv](https://github.com/samvera-labs/bulkrax/files/7376400/185_bc.csv)<br> with only required values: [185_bc_round_trip.csv](https://github.com/samvera-labs/bulkrax/files/7376402/185_bc_round_trip.csv) | …
> Respect nil values

- lib/generators/bulkrax/templates/bin/importer
- lib/generators/bulkrax/templates/config/bulkrax_api.yml
Fixes this error when using the API in development mode on an app configured to talk over port 3000: 
```
Failed to open TCP connection to localhost:80 (Cannot assign requested address - connect(2) for "localhost" port 80) (Faraday::ConnectionFailed)
```
Co-authored-by: Braydon Justice <braydon.justice@1268456bcltd.ca>
> Add port option to bulkrax API/CLI

- app/models/bulkrax/entry.rb
- app/models/bulkrax/rdf_entry.rb
- app/models/concerns/bulkrax/import_behavior.rb
- app/parsers/bulkrax/application_parser.rb
- lib/bulkrax.rb
- lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
- spec/lib/bulkrax_spec.rb
- spec/models/bulkrax/oai_entry_spec.rb
- spec/models/bulkrax/rdf_entry_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
Refactor for #371 
Resolves this TODO comment from `lib/bulkrax.rb`: 
> merge related_children_field_mapping and related_parents_field_mapping into field_mappings, or make them settable per import some other way.
Also, the original changes from #371 did not properly account for mappings where the "from" and the "to" are not the same value (e.g. `'hello' => { 'from' => ['world'] }`)
Now, `related_parents_field_mapping` and `related_children_field_mapping` can be set per parser in the `field_mappings` config, [similar to source_identifier](https://github.com/samvera-labs/bulkrax/wiki/Configuring-Bulkrax#work-identifier-fields-)
> Condense "related" field mapping configs into the field_mappings

- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/oai_entry.rb
- app/models/bulkrax/rdf_entry.rb
- app/models/bulkrax/xml_entry.rb
- app/models/concerns/bulkrax/has_matchers.rb
- app/models/concerns/bulkrax/import_behavior.rb
- spec/factories/bulkrax_importers.rb
- spec/models/bulkrax/csv_entry_spec.rb
Use existing logic to parse parent-child relationships instead of doing it manually 
Related: #371 
**Changes include:** 
- Remove manual parsing of relationship data (`#add_relationships`) 
- Add `#related_parents_parsed_mapping` and `#related_parents_parsed_mapping` to new `#supported_bulkrax_fields` method so they can be processed by `#add_metadata` 
- Respect the presence of `index` in `#set_parsed_data` for non-object data
> Support numerated headers for parent-child relationship imports

- app/models/bulkrax/csv_entry.rb
- spec/models/bulkrax/csv_entry_spec.rb
Remove logic that directly conflicts with logic introduced in #374
> Don't skip blank values when parsing CSV metadata

- .rubocop.yml
- app/models/bulkrax/csv_collection_entry.rb
- app/models/concerns/bulkrax/import_behavior.rb
- app/parsers/bulkrax/csv_parser.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
Resolves #401 
Resolves #402 
Verified that I was able to created collections and associated them to works using the old and new ways.
> i401 i402 fix bugs with collection_field_mapping and parent-child jobs

- app/parsers/bulkrax/csv_parser.rb
When creating collections with the collection_field_mapping way, the collection's title would be displayed as an array. This PR allows it the default metadata value be saved as a string instead, so that it gets displayed properly.
> Collection title should be a string instead of an array

- app/models/concerns/bulkrax/download_behavior.rb
content-type for export download is application/zip so content-dispos should be attachment
> fixes export zip downloads inline #389

- app/models/bulkrax/csv_file_set_entry.rb
- app/parsers/bulkrax/csv_parser.rb
- spec/factories/bulkrax_exporters.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
When exporting "All" or from an Importer, include Collection and FileSet records in the export. 
**NOTE:** when exporting from an importer, Collections that were imported using the deprecated `collection_field_mapping` are not included in the export
> Add Collections and FileSets to CSV exports

- app/parsers/bulkrax/csv_parser.rb
This PR fixes the "pending" status bug. While importing a csv work and collection, the importer's index page would remain "pending" even though the work and collection had completed successfully. 
We need to call the #increment_counters method before the ImportCollectionJob since it's a perform_now job.
> call increment_counters before perform_now job

- app/views/bulkrax/exporters/index.html.erb
- app/views/bulkrax/importers/index.html.erb
Clicking on the back button on an importer's show page, to return to the index pages, would produce duplicate elements within the UI. 
https://github.com/samvera-labs/bulkrax/issues/350
> i350 - fix for multile ui elements on index page

- app/assets/javascripts/bulkrax/importers.js.erb
Even when adding many files to an import, only the first ten are listed. I think this was just a typo.
> Show all added cloud files, not first ten

- app/models/concerns/bulkrax/importer_exporter_behavior.rb
- app/parsers/bulkrax/csv_parser.rb
co-author @sephirothkod 
Even though [current_run](https://github.com/samvera-labs/bulkrax/pull/420/files#diff-4eda1ce8a9d73a758fd0c6bf408cc877e883155d5a3472d372d13c3adab36ec0R25) was being saved, we needed to find it again for it to have the latest count updates from the database on each iteration. 
ref: https://github.com/samvera-labs/bulkrax/issues/421
> i421 - enqueued entries count bug

- app/models/bulkrax/csv_entry.rb
- app/models/concerns/bulkrax/has_matchers.rb
Previously, when importing using the `visibility` CSV column, the value set on the importer would always be used, even when a row declared a different visibility within the metadata. 
Changes include: 
- Adding fallback visibility _after_ parsing metadata 
- Add visibility to Bulkrax's list of supported fields 
- This is necessary because `field_supported?("visibility")` returns `false` without this
> fix visibility so it gets respected when importing

- app/models/bulkrax/csv_entry.rb
- app/parsers/bulkrax/csv_parser.rb
- spec/fixtures/csv/failed_collection.csv
- spec/parsers/bulkrax/csv_parser_spec.rb
Closes #417 
Use `#perform_later` for collections that are not imported using the `collection_field_mapping`
> 417 Do not stop all collections from importing when one fails

- .github/workflows/branches.yml
- .github/workflows/release_labels.yml
- .github/workflows/test.yml
- CONTRIBUTING.md
Closes #435 
Adds [this action](https://github.com/marketplace/actions/label-checker-for-pull-requests) for verifying Release Labels on PRs
> 435 Add check for presence of Release Notes labels on PRs

- app/models/bulkrax/importer_run.rb
related: #439 
I dropped, created, migrated and seeded the db on louisville. afterwards, it [updated the schema](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/66). after this change, I was unable to even access the importer dashboard page because of the error below.
on the related pr above, we removed the default value of the `parents` array, which is what I believe makes the serialization no longer necessary.
- an import can be successfully run after updating bulkrax in a client app to the `9a12f142` commit on `main`
| before | after |
| --- | --- |
| ![Screen Shot 2022-03-17 at 2 44 19 PM](https://user-images.githubusercontent.com/29032869/158903537-d9e78496-6184-4cc2-adc8-a624edd88a41.png) | ![image](https://user-images.githubusercontent.com/29032869/158904717-7a99095b-4453 …
> remove parents column serialization in the importer run

- app/models/bulkrax/csv_entry.rb
- app/models/concerns/bulkrax/export_behavior.rb
- spec/models/bulkrax/csv_entry_spec.rb
> i425 Export FileSet filenames (and i424 fix)

- Gemfile.lock
- lib/bulkrax/version.rb
- spec/models/bulkrax/csv_entry_spec.rb
> Major version bump v3.0.0.beta1

- app/factories/bulkrax/object_factory.rb
- app/models/bulkrax/csv_entry.rb
- spec/jobs/bulkrax/importer_job_spec.rb
After merging, release `v3.0.0.beta2` 
Changes: 
- Don't throw errors when Collection relationships are blank (e.g. `[""]`) 
- Change export join character to pipe instead of semicolon 
- Many recent projects have been using the pipe character since semicolons are often valid metadata 
- This change brings joining on export inline with changes in #441
> Fix collection relationship importing, change export join character

- app/models/bulkrax/importer_run.rb
- app/models/concerns/bulkrax/import_behavior.rb
- db/migrate/20220330165510_remove_array_true_from_importer_run_parents_column.rb
- spec/models/bulkrax/csv_entry_spec.rb
- spec/models/bulkrax/importer_run_spec.rb
- spec/test_app/db/schema.rb
After merging, release v3.0.0.beta3
`ImporterRun#parents` was being set to a String instead of an Array: 
```ruby
i.last_run.parents
=> "[]irc1irc1" # should be ["irc1", "irc1"]
```
Serialize `ImporterRun#parents` as an Array. This fixes this bug: 
This bug was not a problem on projects using postgres because postgres natively supports storing data as arrays. However, other databases (e.g. mysql) do _not_ natively storing data as arrays. Because of this, `#serialize` is preferable since it has more compatibility
> Fix NoMethodError on ImporterRun#parents

- app/factories/bulkrax/object_factory.rb
- app/jobs/bulkrax/create_relationships_job.rb
- app/jobs/bulkrax/import_file_set_job.rb
- app/models/concerns/bulkrax/dynamic_record_lookup.rb
- app/models/concerns/bulkrax/file_factory.rb
- app/models/concerns/bulkrax/import_behavior.rb
- spec/jobs/bulkrax/create_relationships_job_spec.rb
- spec/jobs/bulkrax/importer_job_spec.rb
- spec/models/concerns/bulkrax/dynamic_record_lookup_spec.rb
I imported the same collection on 3 different importers while upgrading bl. the first time the collection wasn't created. so on the 3rd importer where the collection had been created, it was still finding the entry from the first importer. and therefore `entry.factory.find` was nil when it shouldn't have been.
- get the entry from the current importer and not the first entry, if applicable
- return the entry and fedora record from `find_record`
- update code around importing FileSet rows
| works | file set |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/29032869/162345874-6b687ce0-7b85-4566-b627-23e63994b7fe.png) | ![image](https://user-images.githubusercontent.com/29032869/162345847-4b643e4f-ea90-4a09-a991-db172e625852.png)|
> accurate-relationship-forming

- app/models/bulkrax/csv_entry.rb
- use `source_identifier` instead of `work_identifier`
- `source_identifier` is the value on the csv and the "from" in bulkrax.rb
- `work_identifier` is the "to" value in bulkrax.rb
- these are not always the same
> identifier-mixup

- app/controllers/bulkrax/exporters_controller.rb
- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/exporter.rb
- app/views/bulkrax/exporters/_form.html.erb
- app/views/bulkrax/exporters/show.html.erb
- config/locales/bulkrax.en.yml
- db/migrate/20220413180915_add_generated_metadata_to_bulkrax_exporters.rb
- spec/models/bulkrax/csv_entry_spec.rb
- spec/test_app/db/schema.rb
ref: https://github.com/samvera-labs/bulkrax/pull/462
PALS would like to contribute back the following work: 
1. The ability to export generated metadata, like: created_date, date_uploaded, date_modified
From the export form, if a user checks to include generated metadata, the csv will get exported with a generated metadata column headers and datetimestamps as their values.
> Export generated metadata

- app/models/bulkrax/importer_run.rb
- app/models/concerns/bulkrax/import_behavior.rb
- db/migrate/20220301020307_add_parents_to_bulkrax_importer_runs.rb
- db/migrate/20220330165510_remove_array_true_from_importer_run_parents_column.rb
- spec/models/bulkrax/csv_entry_spec.rb
- spec/test_app/db/schema.rb
remove database column for parents and just use relationships look up each time.
> streamline parents lookup per run.

- app/models/bulkrax/csv_entry.rb
- rename `possible_collection_ids` to `collection_identifiers` because...that's what they are now
> semantic-collections

- app/factories/bulkrax/object_factory.rb
- app/jobs/bulkrax/create_relationships_job.rb
- app/models/concerns/bulkrax/dynamic_record_lookup.rb
- spec/jobs/bulkrax/create_relationships_job_spec.rb
- spec/models/concerns/bulkrax/dynamic_record_lookup_spec.rb
ref: #471 && #475
- users can add a child work to a preexisting collection using the collection's id
- users can add a child work to a preexisting work using the preexisting work's id
- users can add a child collection to a preexisting collection using the preexisting collections's id
| work to collection | work to work |  collection to collection |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/164119946-40206872-b467-470e-b273-d578366a9474.png) | ![image](https://user-images.githubusercontent.com/29032869/164119886-267269f2-d517-4e17-883e-4459cd40338b.png) | <img width="1169" alt="image" src="https://user-images.githubusercontent.com/29032869/165091135-c5864a2d-36d5-4fea-b4bd-af08bfe5de01.png"> |
> unable to reference a parent work/collection by id in 3.0+

- app/models/bulkrax/csv_entry.rb
Inconsistent error on first run of import: NoMethodError - undefined method '[]' for nil. 
Error clears after a re-run.
Found that the raw metadata of imported entries returns a nil value due to import jobs still loading, hence the NoMethodError on the first run and not the rerun. Issue is resolved with `&.` that prevents block from erroring out
> Random nomethoderror import

- .github/workflows/release_labels.yml
According to [this commit](https://github.com/samvera-labs/cla-bot/commit/4bc9dd5a3ebe0230405ae4d7a27c2a21f525d782) in the cla-bot, CLAs are no longer required by Samvera. This PR removes the GitHub workflow that required the `cla-lable` to be present on all PRs
> Remove check for CLA from CI

- app/parsers/bulkrax/csv_parser.rb
Collections are not getting exported in projects whose solr suffixes differ than the hard-coded `_sim` (e.g. `_tesim`). To avoid this, we should refer to the solr field dynamically
> Use dynamic solr field for work_identifier

- app/models/bulkrax/csv_entry.rb
Inconsistent error on first run of import: `NoMethodError - undefined method '[]' for nil`
Error clears after a re-run.
Found that the raw metadata of imported entries returns a `nil` value due to import jobs still loading, hence the `NoMethodError` on the first run and not the rerun. Issue is resolved with `&.` that prevents block from erroring out.
> Random NoMethodError on import

- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/csv_file_set_entry.rb
- spec/models/bulkrax/csv_file_set_entry_spec.rb
Display a more descriptive error message when `FileSet` entries are missing a parsed filename. This replaces the ambiguous `NoMethodError` that was previously being thrown:
> Better error message for FileSets missing files

- app/factories/bulkrax/object_factory.rb
- app/jobs/bulkrax/create_relationships_job.rb
- spec/jobs/bulkrax/create_relationships_job_spec.rb
Separated relationships handling away from `ObjectFactory` and into `CreateRelationshipsJob` that was creating an `ActiveFedora::ObjectNotFoundError`
Relationships include:
- Collection Parent -> Collection Child
- Collection Parent -> Work Child
- Work Parent -> Work Child
> Remove legacy collection relationships logic from object factory

- app/jobs/bulkrax/create_relationships_job.rb
- app/models/bulkrax/importer.rb
- app/models/concerns/bulkrax/import_behavior.rb
- spec/jobs/bulkrax/create_relationships_job_spec.rb
`Hyrax::Collections::NestedCollectionPersistenceService#persist_nested_collection_for` is only meant to be used for Collection-to-Collection relationships. Because of this, Collection-to-Work relationships were broken. 
Instead, use [Collection#add_member_objects](https://github.com/samvera/hyrax/blob/v2.9.6/app/controllers/hyrax/dashboard/collection_members_controller.rb#L29), which is used in the `Hyrax::Dashboard::CollectionMembersController`
> Fix Collection-to-Work relationship assigning

- app/models/bulkrax/csv_entry.rb
- app/models/concerns/bulkrax/import_behavior.rb
- lib/bulkrax.rb
- lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
- spec/models/bulkrax/csv_entry_spec.rb
- spec/test_app/app/models/work.rb
- spec/test_app/config/authorities/rights_statements.yml
For default Hyrax local Questioning Authority controlled fields (`:rights_statement` and `:license`): 
- Use appropriate protocol (`https` or `http`) depending on IDs in `config/authorities/` YAML files 
- Add missing trailing slashes
- Remove duplicate `:removed_image_path` from `Bulkrax` config
> Account for commons mistakes when importing controlled Questioning Authority fields

- app/parsers/bulkrax/csv_parser.rb
Fix Solr query for exporting from importers. Add double quotes around Entry identifiers to ensure query only returns exact matches 
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details> 
<details><summary>Multiple entries</summary>
</details>
> Fix exports from importers including unrelated records

- app/models/concerns/bulkrax/dynamic_record_lookup.rb
- spec/jobs/bulkrax/create_relationships_job_spec.rb
- spec/models/concerns/bulkrax/dynamic_record_lookup_spec.rb
the `importer_id` wasn't actually being used in entry lookup. in my case, there were 2 entries with the same `parent_identifier`, but from 2 different importers. the first entry was exited from before completion so the `parsed_metadata`was nil. this meant that in "dynamic_record_lookup", the first invalid entry was being returned and when `entry.factory.find` was called...it came back nil. 
the before and after is demonstrated below. (look at the 4 red boxes)
> better entry lookup

- app/jobs/bulkrax/create_relationships_job.rb
Fixed a previous change that resulted in an interesting unintended behavior.
`Bulkrax::Importer.find(importer_id).record_status` was removing all `Entries Processed` and adding `Pending` status to all entries even after they are processed.  It seems that since `#record_status` is being called after `ImportWorkJob`, `ImportCollectionJob`, and `ImportFileSetJob`, it is not needed after `CreateRelationshipJob` as the statuses should already set before this job runs.
Before:
After:
> erroneous pending status on import

- app/models/bulkrax/csv_entry.rb
- spec/models/bulkrax/csv_entry_spec.rb
Changes: 
- Use `#key_for_export` instead of always exporting model as `"model"` 
- Export files metadata closer to beginning of CSV instead of at the very end 
- Remove unused `#make_round_trippable` method 
- Move required export metadata into new `#build_system_metadata` method 
- Minor reorganization of `CsvEntry` class
> Use #key_for_export instead of always exporting model as "model"

- app/parsers/bulkrax/csv_parser.rb
If we don't cache `CsvParser#records`, it does the following every time it gets called: 
- Reads all the data from the CSV 
- Saves the Importer object
> Cache CsvParser#records method

- app/models/concerns/bulkrax/file_set_entry_behavior.rb
Don't spawn relationship jobs for FileSets; their parent work is set up in `ObjectFactory#create_file_set`
> Do not spawn relationship jobs for FileSets

- app/factories/bulkrax/object_factory.rb
ref: [i544](https://github.com/samvera-labs/bulkrax/issues/544)
There have been reported incidences imports and round trips resulted in nil valued depositors. 
This is because #apply_depositor_metadata used to only be called for certain object types. Additionally, it was never called during the update method (aka round trip). The object would get updated to whatever attrs were passed to it. If there is a nil depositor in the data, it would get reset to nil even if the object previously had a depositor. 
I am also noticing that depositor gets exported as nil for Collection and FileSet even when their objects have a value. Looking into that.
row 1 = Work 
row 2 = Collection
row 3 = FileSet
Debugging exporter. Find the collection. Does it have a depositor? => YES
How come it doesn't get …
> Issue-544 - verify depositor presence on imported works

- .github/release.yml
- .github/workflows/release_labels.yml
Make PR label requirements more flexible.
Before, a PR could not have more than one of the required labels. This made it impossible for PRs that had database changes to use the `database-change` label while also describing what impact it will have on the next release (patch, minor, or major version bump). 
With this change, the `bug-fix`, `enhancement`, and `breaking-change` labels will no longer affect the auto-generated release notes, allowing them (and future labels) to be mixed and matched to be used as descriptors. One of the `major-ver`, `minor-ver`,`patch-ver`, or `ignore-for-release` labels is required, making a PRs impact on release notes more explicit.
> GitHub PR Label action improvements

- app/jobs/bulkrax/create_relationships_job.rb
- app/models/bulkrax/importer_run.rb
- app/models/bulkrax/pending_relationship.rb
- app/models/concerns/bulkrax/import_behavior.rb
- db/migrate/20220609001128_rename_bulkrax_importer_run_to_importer_run.rb
- spec/factories/bulkrax/pending_relationships.rb
- spec/models/bulkrax/importer_run_spec.rb
- spec/test_app/db/schema.rb
Let Rails handle database table prefixes with its magic.
An Importer's `PendingRelationship`s (through `ImporterRun`) will no longer cause attempting to destroy the Importer to throw an error. Instead, the Importer's pending relationships will be destroyed alongside it automatically
> Pending relationships do not cause errors when destroying Importers

- app/models/bulkrax/csv_entry.rb
- spec/models/bulkrax/csv_entry_spec.rb
ref: #560
When selecting include_thumbnails? on a bulkrax exporter, the exported csv should have a "thumbnail_file" column. The zip's files directory should contain the thumbnail file, and its name will be referenced in the csv.
> 560 reimplement thumbnail export

- app/models/concerns/bulkrax/status_info.rb
- spec/models/concerns/bulkrax/status_info_spec.rb
The `#failed?` method is used to determine whether the Error accordion should render in the UI. Before, it would match on the presence of the string "fail", meaning that `"Complete (with failures)"` would cause it to return true. This would render the Error accordion on the importer show page, even if the importer itself didn't have any errors on it. 
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
> Do not render empty Error accordian on importers that succeed with failures

- app/parsers/bulkrax/bagit_parser.rb
BagIt gem was creating empty/invalid bags so the line to instantiate a bag was moved after the `next unless` so this won't happen.
> reworked bagit write files to not create empty bags

- .gitignore
- Gemfile
- Gemfile.lock
- app/parsers/bulkrax/application_parser.rb
- bulkrax.gemspec
- lib/generators/bulkrax/install_generator.rb
- spec/parsers/bulkrax/bagit_parser_spec.rb
Export is a first class feature, so we should support its dependencies directly.
> Remove willow_sword as a soft dependency, make rubyzip a full dependency

- app/models/bulkrax/exporter.rb
- app/parsers/bulkrax/csv_parser.rb
- app/views/bulkrax/exporters/_form.html.erb
- app/views/bulkrax/exporters/show.html.erb
- config/locales/bulkrax.en.yml
- spec/models/bulkrax/exporter_spec.rb
ref: #566 
- we can export the metadata of all collections in their own csv (does not apply to the bagit parser)
- we can export collection metadata along with the works in that collection when we choose the "collection" option (does not apply to the bagit parser)
- this will not work for bagit parsing because bags require a file to be present and collections don't have files. this work is actually because of that fact though. exporting all work and fileset metadata is being worked on in #563 if a user wants checksum verification as they export their entire tenant. then they can export all collection metadata with this feature.
- the exporter show page only shows work ids, although the "total works" count is correct. this is being handled on #444 
|| new/edit page | show page | exported …
> 566-collections-metadata-only

- app/parsers/bulkrax/bagit_parser.rb
- spec/parsers/bulkrax/bagit_parser_spec.rb
ref #563 
- exporting all now exports the file set metadata that's related to the work all on the same csv
[export_6_18.zip](https://github.com/samvera-labs/bulkrax/files/8905284/export_6_18.zip)
(the entire database consists of 2 collections, one work, with one fileset attached. we would expect one bag that has a work row and the related fileset row. no reference to the collections at all)
> 563-bagit-export-fileset-metadata

- app/models/concerns/bulkrax/export_behavior.rb
- app/parsers/bulkrax/bagit_parser.rb
Prepending the id onto the filename to avoid duplication errors.  Though this changes the filename they are still coming out as valid bags so it should still satisfy requirements.  Added error handling just in case something really weird happens.
**Work with duplicate filesets**
**Error in console**
**Failed status on Export**
**Failed status on Entry**
**Resulting bag**
> handles bagit bag file exists error and prepends id to data filenames

- app/jobs/bulkrax/export_work_job.rb
- app/models/concerns/bulkrax/export_behavior.rb
- app/parsers/bulkrax/bagit_parser.rb
- spec/parsers/bulkrax/bagit_parser_spec.rb
Bagit exports were erroneously updating the status to 'Complete' when it was not.  That was because the enqueued records were never set correctly and was stuck on zero.  Pulled in `CsvParser#total` to `BagitParser` and found when `limit` is 0, it did not respect it as the same as nil.
This change might need to be reflected in `CsvParser` or better yet, move all duplicate code from each individual parser up to `ApplicationParser`.
> Bagit export status and total fix

- db/migrate/20220609001128_rename_bulkrax_importer_run_to_importer_run.rb
Some MySQL databases were not properly migrating the foreign key with the most recent migration change (`RenameBulkraxImporterRunToImporterRun`), while Postgres ones were. This change makes the migration more universal by manually removing / re-adding the foreign key (and index) manually around the column name change 
#393 fixed a similar issue 
<details><summary>Archive (no longer applicable)</summary>
1. `rails db:migrate:down VERSION=20220609001128`
2. `rails db:migrate`
3. Verify the changes to `db/schema.rb` 
a. `bulkrax_pending_relationships` table<sup>1</sup>
b. `bulkrax_pending_relationships` foreign key<sup>2</sup> 
<sup>1</sup> `bulkrax_pending_relationships` table
```ruby
create_table "bulkrax_pending_relationships", options: "ENGINE=InnoDB DEFAULT CHARSET=latin1", force: …
```
> Fix error when migrating MySQL db (ref #393)

- app/views/bulkrax/exporters/_form.html.erb
ref: #538 
Added `required: true` tag to each input field.  This would prevent the user from continuing if that field is left blank.
|Work Type|Collection|Importer|
|---|---|---|
|<img height="300" alt="Screen Shot 2022-06-24 at 8 30 23 AM" src="https://user-images.githubusercontent.com/19597776/175569896-3cbb8002-7b40-468e-945e-4e7e9e28a66a.png">|<img height="300" alt="Screen Shot 2022-06-24 at 8 30 12 AM" src="https://user-images.githubusercontent.com/19597776/175569907-e5f25638-749d-476d-9f62-1f803b0870d8.png">|<img height="300" alt="Screen Shot 2022-06-24 at 8 29 59 AM" src="https://user-images.githubusercontent.com/19597776/175569916-8bc14cf9-d76d-40c2-83cf-9ff065b61553.png">|
> added required tag to form fields

- app/views/bulkrax/exporters/_form.html.erb
References[ bulkrax 538](https://github.com/samvera-labs/bulkrax/issues/538). Hidden fields cannot be required.
reverse https://github.com/samvera-labs/bulkrax/pull/575 to be handled at a later point.
> Undo require form fields

- README.md
A couple links to the Bulkrax wiki did not resolve, so I replaced them with what seemed like the most obvious candidates. Also, since Samvera has dropped the CLA requirement, I removed the mention of it I found.
> Fix wiki links, remove CLA mention

- app/controllers/bulkrax/exporters_controller.rb
- app/models/bulkrax/exporter.rb
- app/models/concerns/bulkrax/export_behavior.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/views/bulkrax/exporters/_downloads.html.erb
- app/views/bulkrax/exporters/index.html.erb
- app/views/bulkrax/exporters/show.html.erb
- lib/tasks/bulkrax_tasks.rake
- spec/jobs/bulkrax/importer_job_spec.rb
- spec/models/bulkrax/exporter_spec.rb
- spec/parsers/bulkrax/bagit_parser_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
ref: https://gitlab.com/notch8/palni-palci/-/issues/466
- csv formatted exports will have a maximum of 1000 records per csv
- if there are multiple csv's, each one along with its related "files" folder, will be in its own zip file
- bagit formatted exports will have a maximum of 1000 records per zip. 
- there will still only be 1 work per csv, along with its child file sets
- a single zip will contain multiple bags
- now that there are potentially several zip files created from a single export, there is a drop down of files on the index page
- selecting a zip file and then pressing "download" will download that particular zip file
- the same applies to the exporter show page
<details>
<summary> exporter index page </summary>
</details>
<details>
<summary> exporter show page </summary> …
> Split downloads by size

- app/models/bulkrax/exporter.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- config/locales/bulkrax.en.yml
- spec/models/bulkrax/exporter_spec.rb
- spec/parsers/bulkrax/bagit_parser_spec.rb
ref: https://gitlab.com/notch8/palni-palci/-/issues/466
#566 #590 
- remove references to "collections_metadata"
- export collections through bagit too when exporting "all" or by collection
export of 2 works, with file sets, in a collection (CSV): [export_2_17_1.zip](https://github.com/samvera-labs/bulkrax/files/9133245/export_2_17_1.zip)
export of 2 works, with file sets, in a collection (BAG): [export_3_13_1.zip](https://github.com/samvera-labs/bulkrax/files/9132960/export_3_13_1.zip)
| csv | bag |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/179547142-e3f8b297-00fd-4686-81b1-3134cdfa4ec5.png) | ![image](https://user-images.githubusercontent.com/29032869/179539656-9f9aee55-673e-40cd-88ef-98d4089d4730.png) |
> 566 collection metadata exporting

- app/models/bulkrax/exporter.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/views/bulkrax/exporters/show.html.erb
- spec/models/bulkrax/exporter_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
- do not include child collections as part of the @work_ids
- include child collections as part of the @collection_ids
- remove remaining/returned references to "collections metadata"
- return guard clause for bagit files on export
- 1 parent collection
- 1 child collection
- 2 child works, with 6 file sets between them
(the bag image only shows one of the child works with its associated files)
csv: [export_2_19_1.zip](https://github.com/samvera-labs/bulkrax/files/9134433/export_2_19_1.zip)
bag: [export_3_21_1.zip](https://github.com/samvera-labs/bulkrax/files/9134394/export_3_21_1.zip)
| csv | bag|
| --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/179576093-626474f1-6280-462e-8c30-03a1552638c2.png) | ![image](https://user-images.githubusercontent.com/29032869/179 …
> export-child-collections

- app/parsers/bulkrax/application_parser.rb
- spec/parsers/bulkrax/application_parser_spec.rb
ran into this issue while running this [rake task](https://github.com/samvera-labs/bulkrax/blob/main/lib/tasks/bulkrax_tasks.rake) on pals for all exporters that were exporting from a collection after updating to `v4.1.0`
sentry error: https://sentry.notch8.com/sentry/pals/issues/142067/
- account for when `importerexporter.field_mapping` is `nil` in the "get_field_mapping_hash_for" method
> undefined-method-length-for-nil-class

- app/parsers/bulkrax/csv_parser.rb
ran into this issue while running this [rake task](https://github.com/samvera-labs/bulkrax/blob/main/lib/tasks/bulkrax_tasks.rake) on pals for all exporters that were exporting from a collection after updating to `v4.1.0`
sentry error: https://sentry.notch8.com/sentry/pals/issues/142068/
before https://github.com/samvera-labs/bulkrax/pull/597, child collections were exported as a CsvEntry class instead of CsvCollectionEntry. this means that when that importer/exporter is run again, the old entry still exists, but a new one is created as well. the newer entry is at index 0, so calling `uniq` on the identifier value (as seen below), returns index 0.
- ignore misidentified collection entries when writing files from the csv parser
>  ignore-misidentified-collection-entries

- app/parsers/bulkrax/application_parser.rb
sentry issue: https://sentry.notch8.com/sentry/pals/issues/142039/
- remove existing zip files to avoid the Zip::EntryExistsError
> zip-entry-exists-error

- app/parsers/bulkrax/csv_parser.rb
sentry: https://sentry.notch8.com/sentry/pals/issues/142087/
- account for custom work types in #sort_entries
> escape-nil-comparisons

- app/parsers/bulkrax/csv_parser.rb
sentry error: https://sentry.notch8.com/sentry/pals/issues/142081/
- return from #store_files in the csv parser if the record is not found
> avoid-ldp-gone-when-writing-files-on-export

- app/parsers/bulkrax/csv_parser.rb
https://github.com/samvera-labs/bulkrax/pull/603 did not resolve the [ldp::gone issue](https://sentry.notch8.com/sentry/pals/issues/142081/) after deploying `v4.2.0`. 
- specifically rescue the Ldp::Gone error in #store_files of the csv parser
> ldp-gone-part-2

- app/parsers/bulkrax/application_parser.rb
- lib/tasks/bulkrax_tasks.rake
- spec/parsers/bulkrax/application_parser_spec.rb
ref #611 
- use the tenant name in the parser export base_path in hyku apps
| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/177658537-c20d13f5-092f-46b8-a326-9972d68725bf.png) | ![image](https://user-images.githubusercontent.com/29032869/181080181-853627b4-b11f-4a1d-a6e0-ed1df66e50fb.png)|
the spec for this work is being done in #613
> 611-base-path-per-tenant

- app/parsers/bulkrax/application_parser.rb
- keep the import and export paths the same
apps that were using the correct ENV variable, did have the export AND import paths separated by tenant name
> 611-base-path-per-tenant-v2

- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
this might be the fix to the issue with pals constantly retrying 2 exporters. per the screen shot below, `.uri` is getting called on a nil class. `.uri` only shows up 3 times in the code. the bagit parser, csv parser and object factory inside of the `#create_file_set` method. we aren't creating, so I figure that's not the problem.
I'd think we should always have a file...but we're doing a check for "if file_set.original_file.blank?" in the `#filename` method in export_behavior.rb too. so I figured there must be a case where it doesn't exist.
- account for a missing original_file on csv and bagit export
> account-for-missing-original-file-on-export

- lib/bulkrax.rb
- spec/lib/bulkrax_spec.rb
- check for the configured import and export paths first
``` ruby
config.import_path = 'tmp/my-other-import-path'
```
> 354-use-configured-base-paths

- app/assets/javascripts/bulkrax/exporters.js
- app/views/bulkrax/exporters/_form.html.erb
Ref: https://github.com/samvera-labs/bulkrax/issues/538
Original PR: https://github.com/samvera-labs/bulkrax/pull/575 (see for additional screenshots)
- uncomment required attr for exporter from fields
- add javascript to handle required attrs while hidden
- original pr did not have javascript to handle required fields while hidden and thus was reverted in https://github.com/samvera-labs/bulkrax/pull/580 because it prevented the use from moving on to the next page
> 🐛 add `required` for `Export From` fields

- app/factories/bulkrax/object_factory.rb
ref #639 
- pass in `attrs` to the actor stack since it contains the visibility of the individual filesets
- a pr/override needs to be made in Hyrax `FileSetActor` to make this work in projects
> pass attrs to actor stack to be used for visibility of filesets

- lib/bulkrax.rb
By requiring this file, upstream applications can then interrogate what
version of Bulkrax is running.  This can be helpful for coordinating
local overrides in the application that can/should/will be merged into
Bulkrax but due to time constraints are not immediately available.
See [Responsible Monkey Patching of Ruby Methods // Take on Rules][1]
for some further details
Closes samvera-labs/bulkrax#641
[1]:(https://takeonrules.com/2022/07/06/responsible-monkey-patching-of-ruby-methods/)
> Ensuring that we load the Bulkrax::VERSION

- app/factories/bulkrax/object_factory.rb
ref: #646 
Import a csv with file set in its own row. If the FileSet row has a remote_files column, it should download those files and attach it to the FileSet. 
Sample file: 
[cats-2.csv](https://github.com/samvera-labs/bulkrax/files/9480243/cats-2.csv)
Downloaded file: 
UPDATE csv/importer - it should update the images seen above.
[update-cats-2.csv](https://github.com/samvera-labs/bulkrax/files/9481226/update-cats-2.csv)
This produces a Sidekiq error from a [hyrax](https://github.com/samvera/hyrax/blob/main/app/jobs/visibility_copy_job.rb#L12) misspelling. [This method](https://github.com/samvera/hyrax/blob/b034218b89dde7df534e32d1e5ade9161e129a1d/app/services/hyrax/visibility_propagator.rb#L39) probably should get updated to '[propagate](https://github.com/samvera/hyrax/search?q=propag …
> i646 - process remote files for filesets

- app/factories/bulkrax/object_factory.rb
Minor update to explicitly call URI.open instead of open, as suggested via a deprecation warning msg.
> call URI.open due to deprecation warning msg

- app/matchers/bulkrax/application_matcher.rb
- app/models/bulkrax/csv_entry.rb
- app/parsers/bulkrax/csv_parser.rb
- lib/bulkrax.rb
- lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
Prior to this commit, we had "magic" strings/regexs sprinkled throughout the code.  This change now moves that towards a consistent and configurable interface.
There are two nuances:
1. The collections title split now includes a new default (e.g. `;`) in the split.  That may introduce a bug.
2. This preserves the ability to specify `split: true` and use the default; which creates the least invasive change for downstream adopters.
Closes #429, #213
> Adding Bulkrax config for multi-value split/join delimiters

- db/migrate/20211203195233_rename_children_counters_to_relationships.rb
- db/migrate/20211220195027_add_file_set_counters_to_importer_runs.rb
- db/migrate/20220118001339_add_import_attempts_to_entries.rb
- db/migrate/20220119213325_add_work_counters_to_importer_runs.rb
- db/migrate/20220301001839_create_bulkrax_pending_relationships.rb
- db/migrate/20220303212810_add_order_to_bulkrax_pending_relationships.rb
- db/migrate/20220412233954_add_include_thumbnails_to_bulkrax_exporters.rb
- db/migrate/20220413180915_add_generated_metadata_to_bulkrax_exporters.rb
- db/migrate/20220609001128_rename_bulkrax_importer_run_to_importer_run.rb
- spec/test_app/db/migrate/20220726162605_create_site.rb
- spec/test_app/db/migrate/20220726164334_create_account.rb
Downgrades the migration versions from 5.2 to 5.1 specifically for atla since they are running on rails/activerecord 5.1.6.
> downgrade-migration-versions-to-five-point-one

- app/models/bulkrax/importer.rb
- app/parsers/bulkrax/application_parser.rb
Prior to this commit, we had an if statement that would check if the given parser was a `Bulkrax::CsvParser`, if so it would go down one logic pathway.  If not, it would call a different pathway.  Each pathway required knowledge of the implementation details of the parser.  The `Bulkrax::CsvParser` required knowledge of a non-public API setup (e.g. a method not defined on `Bulkrax::ApplicationParser`).
With this commit, we're favoring a single entry point for all parsers. Moving the logic down to the parser and allowing for polymorphism of the `Bulkrax::CsvParser` to provide it's different implementation.
One additional change is calling save on the importer before we create the objects.  This was something not called in the `Bulkrax::CsvParser` and based on the comment could have created …
> Refactoring to remove conditional

- app/models/bulkrax/importer.rb
A bug was found with the following scenario:
A client only had the necessary field mappings set (bulkrax_identifier, children, and parents). 
Because of this, [#mapping](https://github.com/samvera-labs/bulkrax/blob/main/app/models/bulkrax/importer.rb#L60-L72) would only return the field mapping. This caused an issue because [matcher](https://github.com/samvera-labs/bulkrax/blob/e88d0ea349afda5b3068836aa36ef86c93d4c62d/app/models/concerns/bulkrax/has_matchers.rb#L32) would return nil for all other imported values.
Because [it](https://github.com/samvera-labs/bulkrax/blob/e88d0ea349afda5b3068836aa36ef86c93d4c62d/app/models/concerns/bulkrax/has_matchers.rb#L44) was nil at the time of assigning the value, if the property was singular or multiple it would never process the split method to make …
> Merge default field mapping in with field mapping

- app/models/bulkrax/csv_entry.rb
- spec/fixtures/csv/mixed-case.csv
- spec/models/bulkrax/csv_entry_spec.rb
Prior to this commit, we were leveraging the built in header_converters method of `:symbol`; which converts headers to symbols by removing "." and converting all upper case characters to lower case.
After this commit, we use a more explicit converter that doesn't perform string transformations.
Closes #669
> Convert csv headers by explicit lambda

- app/factories/bulkrax/object_factory.rb
In UTK, we were getting a `Hyrax::VisibilityPropagator::NullVisibilityPropogator` error for remote files that was triggered by a misspelling.  Conveniently, this led to the question of why is it even hitting the `NullVisibilityPropogator` in the first place?  Turns out, the `FileSet` that comes in did not have a parent because of the logic in Bulkrax.
This PR swaps the logic so the `FileSet` should have a parent prior to hitting the `Hyrax::VisibilityPropagator`
> Fix `Hyrax::VisibilityPropagator` error for remote files

- app/models/concerns/bulkrax/import_behavior.rb
- lib/bulkrax.rb
- lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
this is a first step toward #672 and valkyrie support. we want to be able to drop in an ObjectFactory implementation that finds and saves using Valkyrie instead of ActiveFedora.
> add configuration for using a custom ObjectFactory

- app/controllers/bulkrax/importers_controller.rb
- app/parsers/bulkrax/oai_dc_parser.rb
Prior to this commit, the `metadata_prefix` passed on `OAI::Client.new` was discarded.  In the current code, that option is not processed.  It is instead a parameter to pass to the OAI verb
action (e.g. `ListIdentifiers` and `GetRecords`).
With this commit, we ensure that we pass the `metadata_prefix` to the specific verb.
https://github.com/code4lib/ruby-oai/blob/d0303be9800e7247532286330cf3b0cf135f19d7/lib/oai/client.rb#L86-L121
Closes https://github.com/samvera-labs/bulkrax/issues/676
> Ensuring metadata_prefix option is correctly passed

- app/jobs/bulkrax/create_relationships_job.rb
Ref https://github.com/scientist-softserv/utk-hyku/issues/245
The use of the graph indexer in hyrax 3.x + turns off the nesting indexer, and means that reindex_extent is not defined. This is fixed by adding a guard on the method, which allows the relationships job to complete normally.
**Before:**
> Guard on reindex_extent assignment

- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/entry.rb
- app/models/bulkrax/oai_entry.rb
- app/models/bulkrax/rdf_entry.rb
- app/models/bulkrax/xml_entry.rb
- lib/bulkrax.rb
- spec/lib/bulkrax_spec.rb
Prior to this commit, when someone would upload a CSV it might have a column name that included the tricksy, invisibile [Byte Order Mark][1]. The manifestation was that you could look at the raw metadata and see a key called `"file"` however when checking `raw_metadata.key?("file")` the result was `false`.
To find this `entry.raw_metadata.keys.first.chars.map(&:chr)` I got `["", "f", "i", "l", "e"]` where the first value of that array was a [Byte Oder Mark][1].
With this commit, we're handling both how we persist and how we load persisted serialized data.  This follows on the documentation for the `ActiveRecord::Base.serialize` method.
It's envisioned that we might have more characters to sanitize.
Closes: samvera-labs/bulkrax#688
Related to: scientist-softserv/adventist-dl#179
[1]: …
> Normalizing serialized data for BOM characters

- app/jobs/bulkrax/import_work_job.rb
Prior to this commit, when we encountered a
`Bulkrax::CollectionsCreatedError`, we would reschedule the same job with a 1 minute delay.  However, if the underlying issue was never resolved, we would continually reschedule without fanfare this failing job.
With this commit, we provide 3 logged reschedules, then if that fails we raise an exception break the infinite cycle.  By breaking the cycle, then the upstream Sidekiq handler can determine if it should be thrown into the `Retry` queue (where the jobs that raise exceptions go).
We discovered this in Adventist watch 100 or scheduled jobs run very fast, and apparently continually rescheduling themselves.
Closes #691
> Removing ∞ silent retries of Bulkrax::ImportWorkJob

- app/controllers/bulkrax/importers_controller.rb
- app/models/concerns/bulkrax/file_factory.rb
ref #690
File sets' files were not being updated while their metadata were
File sets' files are now being updated as well as their metadata
> make update remote files work for file sets

- app/parsers/bulkrax/oai_dc_parser.rb
Prior to this commit, we didn't capture the raw metadata of works parsed via OAI-PMH.
With this change, we now capture that information.
Below is an example showing that we need to use the record's `metadata` as a string.
```ruby
gem "oai"
require 'oai'
client = OAI::Client.new(
"http://oai.adventistdigitallibrary.org/OAI-script",
headers: { from: "jeremy@scientist.com" },
parser: 'libxml')
opts = {
metadata_prefix: "oai_adl",
set: "adl:issue"
}
records = client.list_records(opts)
records.each_with_index do |r, i|
puts "Working on record ##{i+1}"
puts "Metadata:\n#{r.metadata.to_s}"
end
```
> Capturing raw metadata for OAI parsing of works

- app/models/bulkrax/oai_entry.rb
- spec/models/bulkrax/oai_entry_spec.rb
a086164abe2b6f6ac79d81e1ef54c65ef8071136
Let's say we have nodes with the following names (and order): `shape`, `model`,
`smell`
Prior to this commit, as we were reading through the record's metadata
when we were processing `shape` we would use the default `factory_class`
to check if `shape` was a valid field.  Then we'd use the value of
`model` to derive the `factory_class`.  And when we then processed
`smell` we'd be using the newly derived `factory_class` from the `model`
node.
With this commit, we first establish the `factory_class` from the
`model` node.  Then we again process the all the nodes to parse the
metadata.  This ensures that both `shape` and `smell` are parsed
against the expected `factory_class`.
Further, I have made a few refactorings that should ease upstream
overrides …
> Ensuring OAI parser sets factory class then parses

- app/models/bulkrax/xml_entry.rb
- spec/models/bulkrax/xml_entry_spec.rb
This commit for changing the `Bulkrax::XmlEntry` is the sibling to the changes made to `Bulkrax::OaiEntry` (see SHA 35970cee).  The salient information is pulled as a quote from that commit:
> Prior to this commit, as we were reading through the record's metadata
> when we were processing `shape` we would use the default
> `factory_class` to check if `shape` was a valid field.  Then we'd use
> the value of `model` to derive the `factory_class`.  And when we then
> processed `smell` we'd be using the newly derived `factory_class` from
> the `model` node.
>
> With this commit, we first establish the `factory_class` from the
> `model` node.  Then we again process the all the nodes to parse the
> metadata.  This ensures that both `shape` and `smell` are parsed
> against the expected …
> Ensuring XML parser sets factory class then parses

- app/factories/bulkrax/object_factory.rb
- lib/bulkrax.rb
- spec/factories/bulkrax/object_factory_spec.rb
There are three changes in this commit:
1. Exposing a class attribute
2. Scouring attribute hash
3. Extracting a method
**Exposing a class attribute**
This was added to allow for easier testing of a private method.  It also "exposes" a hidden assumption in a private method; turning that assumption into a telegraphed potential configuration point.
**Scouring attribute hash**
This resolves the reported problem by @eporter23:
> When testing an import on 9/16/22, the work row failed to validate,
> returning an error regarding "invalid entry for administrative_unit".
>
> The CSV used had the header for that field, but no values entered. Our
> preprocessors output field headers for mapped fields, but sometimes
> there are no values entered for a given header.
>
> -- …
> Scour blank strings from the creation attributes

- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/xml_parser.rb
Prior to this commit, this method was not defined on the `ApplicationParser` yet there was an assumption in the `Bulkrax::ImportersController` and `Bulkrax::ExportersController` that this method existed.
With this commit, we're acknowledging that each parser should implement this method.
In addition this commit adds a `#create_file_sets` method for the `Bulkrax::XmlParser`.  This change mirrors the
`Bulkrax::XmlParser#create_collections` implementation and todo item.
A future state that would be wonderful is to create spec helpers that implementers could use in their specs to ensure a compliant interface. This echoes how Valkyrie does things.
> Adding ApplicationParser#file_set_entry_class to API

- app/parsers/bulkrax/csv_parser.rb
Addresses:
https://github.com/samvera-labs/bulkrax/issues/699
This change might not work with hyrax < 2.8, since it looks like solrizer got merged into activefedora in 12.0.0, so if we need to support those versions of hyrax we will likely need to add some logic in here to decide whether to use solrizer or activefedora.
I also suspect this code might not be getting fully tested, since bulkrax is using hyrax 3, but no tests seem to be impacted by this issue.
> Replace solrizer reference so that feature works with hyrax 3+

- Gemfile
- Gemfile.lock
- app/controllers/bulkrax/entries_controller.rb
- app/controllers/bulkrax/exporters_controller.rb
- app/controllers/bulkrax/importers_controller.rb
- app/views/hyrax/dashboard/sidebar/_bulkrax_sidebar_additions.html.erb
- app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
- lib/generators/bulkrax/install_generator.rb
- spec/controllers/bulkrax/exporters_controller_spec.rb
- spec/controllers/bulkrax/importers_controller_spec.rb
- spec/jobs/bulkrax/create_relationships_job_spec.rb
- spec/jobs/bulkrax/import_file_set_job_spec.rb
- spec/models/bulkrax/csv_file_set_entry_spec.rb
- spec/models/bulkrax/object_factory_spec.rb
- spec/rails_helper.rb
- spec/support/dynamic_record_lookup.rb
- spec/test_app/app/controllers/application_controller.rb
- spec/test_app/app/models/ability.rb
- spec/test_app/app/models/user.rb
- spec/test_app/config/application.rb
Ref https://github.com/scientist-softserv/britishlibrary/issues/227
There are 2 new Ability methods that need to be added to `ability.rb`. If you are using the generator, these methods will be added for you. However, if you are upgrading Bulkrax, you will need to add the following to your `app/models/ability.rb` file above the `can_create_any_works?` method definition. Feel free to adjust the definitions as needed.
```
def can_import_works?
can_create_any_work?
end
def can_export_works?
can_create_any_work?
end
```
> Add Permissions For Bulkrax

- app/parsers/bulkrax/application_parser.rb
- spec/parsers/bulkrax/application_parser_spec.rb
Prior to this commit, I had refactored (in PR #663) logic to remove conditional logic.  However, I had introduced a bug, namely using `parser` and the receiver of `send`.  For the
`Bulkrax::ApplicationParser` there is no parser method.  This resulted in a notable bug.
With this commit, I'm removing `parser` as the receiver of `send` and instead favoring the implicit `self` as the receiver of `send`.
> Fixing bug introduced in #663

- app/models/bulkrax/csv_entry.rb
- spec/models/bulkrax/csv_entry_spec.rb
Address https://github.com/samvera-labs/bulkrax/issues/711
I'm not sure if this is the right approach or not, but it resolves issue #711 by converting the source_identifier field from a relationship to a single value during export. The result is that the export CSV has `work_20230117` as the source_identifier value, rather than `["work_20230117"]`. A `source_1` field is also still added in my testing, not sure if this is desirable or not.
The test is also not great, since its difficult to have fields return Relation without using Work.create, which requires running the whole stack.
> Convert source_identifier from relationship to single value

- app/models/concerns/bulkrax/import_behavior.rb
- spec/models/bulkrax/csv_entry_spec.rb
Resolves https://github.com/samvera-labs/bulkrax/issues/695
* Adds a test that demonstrates the issue
* Updates import to check for multiple versus single valued fields when sanitizing import
> Allow single value fields with controlled vocabs

- app/models/bulkrax/csv_entry.rb
- spec/fixtures/csv/factory_class_test.csv
- spec/models/bulkrax/csv_entry_spec.rb
dbd24b8ee1c6adc5907ef95a93dbe0fdd745ad79
Prior to this commit, if we had configured bulkrax such that we were
allowing for our model import to come from multiple fields
(e.g. `from: ['model', 'work_type']`) and the CSV had `work_type` as the
column name, we would get an error as follows:
```
NoMethodError:
undefined method `method_defined?' for nil:NilClass
```
Tracing this line it is because the `factory_class` is nil.  And if the
model column were to be a later column, any columns that occurred before
we established the factory class may have been skipped.
With this commit, we're echoing the functionality introduced in #705 and #703.
Related to:
- https://github.com/scientist-softserv/britishlibrary/issues/211
- https://github.com/samvera-labs/bulkrax/pull/705
- …
> Ensuring CSV sets factory class before metadata parsing

- app/matchers/bulkrax/application_matcher.rb
Prior to this commit, if we had new parsed fields, we'd need to over-ride a method.
With this commit, we can amend the class attribute of `parse_fields` to add the new method.
> Favoring class_attribute over inline array

- app/jobs/bulkrax/create_relationships_job.rb
- spec/jobs/bulkrax/create_relationships_job_spec.rb
Prior to this commit, we did not expose a means to cascade indexing
deeper than the child work.
With this commit we provide a configuration point for saying "Please
reindex the file sets of the child works we're processing for this
relationship job.
Closes #721
Related to:
- https://github.com/scientist-softserv/louisville-hyku/commit/128a9ef
If you wish to enable reindex child works's file sets during the
CreateRelationshipsJob, you'll want to add the following to your
`config/initializer/bulkrax.rb`:
```ruby
Bulkrax::CreateRelationshipsJob.update_child_records_works_file_sets = true
```
> Adding config to reindex child work's file sets

- app/models/bulkrax/oai_entry.rb
- spec/models/bulkrax/oai_entry_spec.rb
Prior to this commit, the guard condition `return self.collection_ids if collections_created?` served as memoization (e.g. caching the results of an expensive operation).  However, it was not a self-contained memoization (e.g. the method is fully in charge of managing the memoization).  It instead relied on the previous implementation of `#collections_created?`.
Downstream implementations may change `#collection_created?` which could create unintended consenquences of assignign collections based on the OAI spec.  Also, if we look to other implementations in Bulkrax of `#collections_created?` we see that many simply `return true`.
The impact of the previous code is that were someone to make the above change (e.g. always `return true`), we end up never assigning any `setSpec` …
> Ensuring self-contained memoization of method

- app/controllers/bulkrax/entries_controller.rb
- app/controllers/bulkrax/exporters_controller.rb
- app/controllers/bulkrax/importers_controller.rb
- app/helpers/bulkrax/application_helper.rb
Closes #729 and closes #730 
Wrapping references to Hyrax and Breadcrumbs with `is_defined?(::Hyrax)` fixes these errors in non-Hyrax based applications that install Bulkrax.
> check if Hyrax is defined

- app/jobs/bulkrax/create_relationships_job.rb
- app/jobs/bulkrax/delete_job.rb
- app/jobs/bulkrax/export_work_job.rb
- app/jobs/bulkrax/import_file_set_job.rb
- app/jobs/bulkrax/importer_job.rb
- app/models/bulkrax/importer.rb
- app/models/concerns/bulkrax/status_info.rb
- app/parsers/bulkrax/bagit_parser.rb
- spec/jobs/bulkrax/import_file_set_job_spec.rb
Prior to this commit, `status_info` was changing underlying runner information.  This is unexpected behavior given the method name (status_info implies getting information about the status information.)
With this commit, I'm deprecating the `status_info` method with a v6.0.0 deprecation horizon.
> Renaming method to reflect it's state changing nature

- app/helpers/bulkrax/importers_helper.rb
- app/models/bulkrax/importer.rb
- app/views/bulkrax/importers/_form.html.erb
Only uses admin sets in importer creation if Bulkrax is installed in a Hyrax instance.
> only uses admin sets if Hyrax is present

- app/jobs/bulkrax/create_relationships_job.rb
`ordered_members` needed to be transformed into an Array before `#include?` could be called, otherwise we get a `NoMethodError`.
> Fix #add_to_work

- app/models/bulkrax/oai_entry.rb
Prior to this commit, we didn't see the header information.  With this information, we now have the header information.
> Capturing record and header metadata for OAI parser

- lib/bulkrax/entry_spec_helper.rb
Prior to this, you couldn't specify the type of entry you wanted to test (only the :entry_class).  With this change, you can specify which type you want to test.
> Expanding `Bulkrax::EntrySpecHelper` to handle collections

- app/models/bulkrax/exporter.rb
- app/views/bulkrax/exporters/_form.html.erb
Closes #733 
When Bulkrax is installed on a non-Hyrax application, there are errors with the Exporters forms. This PR addresses these errros:
- Exporter form checks to see if Hyrax is defined for worktype, visibility and sipity workflow status
- Exporter model checks to see if Hyrax is defined for workflow status list
- Removes worktype from export_from_list in exporter model because worktype is a Hyrax concept
> exporter errors for non hyrax apps

- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/parsers/bulkrax/parser_export_record_set.rb
- lib/bulkrax/entry_spec_helper.rb
- spec/features/bagit_exporter_spec.rb
- spec/parsers/bulkrax/bagit_parser_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
- spec/parsers/bulkrax/parser_export_record_set_spec.rb
Prior to this commit the `Bulkrax::CsvParser` had complex query logic
for finding the records to process for export.  The logic was memory
inefficient: calling `#current_record_ids` twice (a very expensive
queries that issued many calls to Fedora which could've been a SOLR
query).  In large exports, the processes would spend over 90% of the
time in the finding file sets.
With this commit the `Bulkrax::ParserExportRecordSet` finder logic
echoes the logic once found in `Bulkrax::CsvParser`.  The purpose is to
isolate the place where the SOLR queries happen and to create less
memory intensive processes.
Further the `Bulkrax::ParserExportRecordSet.for` returns an object that
"quacks" like an Array of Arrays, with each inner Array having two
elements.  This makes the testing a bit easier. …
> Adding `Bulkrax::ParserExportRecordSet`

- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/exporter.rb
- spec/models/bulkrax/csv_entry_spec.rb
fefd7344f6ff352197da52babd8dd8b3b814c7fd
47180367b0189580fb3c0b53c0a4c4b696cccb21
fb91aa7e48b01d7c29ee21a9e1bff997adb71430
bea021a361c6bf0cb292bbdfdc1be32144794935
With this commit, we introduce the tested property of
'skip_object_for_model_names' for a parser line.
Related to:
- https://github.com/scientist-softserv/britishlibrary/issues/289
> i289 Exporter Issue

- app/models/bulkrax/csv_entry.rb
- spec/fixtures/csv/entry-causing-problems-in-2.7.6.csv
- spec/models/bulkrax/csv_entry_spec.rb
Prior to this commit, we were relying on the documented `CSV.read`'s `:skip_lines` option.
However, in testing the CSV that is part of this commit, the `CSV.read` would never complete.  Diving deep into the internals, it kept finding lines that upon inspecttion were an empty string.
With this commit, we're moving the skip logic outside of the parser and instead wrapping the results.  This is perhaps less performant, but compared to never completing due to infinite string processing, it actually is more performant.
Further, I have added additional configuration options in the event that this change does not work downstream.  Those configuration options should allow for more immediate relief as the general solution works its way back into Bulkrax.
This refines changes made in …
> Favoring explicit "empty" lines handler

- app/parsers/bulkrax/parser_export_record_set.rb
- spec/parsers/bulkrax/parser_export_record_set_spec.rb
Prior to this commit, we were assuming the `file_set_ids_ssim` did in fact only have ids for FileSets.  [Dear reader, that was a lie][1].
With this commit, we are taking each works's `file_set_ids_ssim` and querying Solr to grab only the ids that are, in fact, for FileSets.
A read through of the prior logic shows that we are grabbing the Fedora objects `file_set_ids`, which is almost certainly excludes child works. See below:
```ruby
ActiveFedora::Base.find(id).file_set_ids.each { |fs_id| @file_set_ids << fs_id }
```
**tl;dr** this is why we can't have nice things.
Related to:
- https://github.com/scientist-softserv/britishlibrary/issues/289
- https://github.com/samvera-labs/bulkrax/pull/749
[1]: https://github.com/samvera/hyrax/blob/64c0bbf0dc0d3e1b49f040b50ea70d177cc9d8f6/app/indexers/hy …
> Ensuring exporter's queried file sets are in fact file sets

- app/jobs/bulkrax/create_relationships_job.rb
This change matches the behavior in Hyrax's `CollectionsMembershipActor`, when a record is added through the UI.
Fixes #758.
> Improve CreateRelationshipsJob's performance by setting reindexing to LIMITED_REINDEX

- app/models/concerns/bulkrax/has_matchers.rb
By default, `ImportBehavior#add_rights_statement` sets the value to an array, which causes an error since `sanitize_controlled_uri_values!` doesn't know to treat it as such.
This whole section needs to be refactored, since the rights statement service can be overridden locally, but this at least un-breaks the default configuration.
> add rights_statement to list of fields with multiple values

- app/parsers/bulkrax/parser_export_record_set.rb
Prior to this commit, when we would query to export file sets we didn't guard for no file sets associated with the works.  In [this importer][1] we saw a SOLR exception about an invalid query.  The SOLR query had the following:
```
fl=id&rows=0&q=has_model_ssim%3AFileSet+AND+id%3A%28%29+&qt=standard
```
In the above, we are querying for FileSets (selecting on the ID field). However there were no candidate file sets (e.g. `rows=0` and `id:()`) associated with the works for the export.
With this commit we guard against running a query for 0 rows.  Which should eliminate the particular problem.
Related to:
- https://github.com/samvera-labs/bulkrax/pull/749
- https://github.com/scientist-softserv/britishlibrary/issues/353
- https://github.com/scientist-softserv/britishlibrary/pull/328
- …
> Adding guard for querying 0 rows for FileSets

- app/matchers/bulkrax/application_matcher.rb
Method doesn't seem to be used anywhere in the code. Deprecating to warn anyone who might be using it, then going to remove in a few months.
> Deprecate parse_resource_type method as it isn't used anymore

- app/models/concerns/bulkrax/importer_exporter_behavior.rb
- app/parsers/bulkrax/application_parser.rb
Note: This does not included tests, which is something that #744  also did not.  However, we have verified the behavior.
Reading the [documentation for the Marcel gem][1], it requires a file handle (e.g. `File.new` or `File.open`) instead of a String.
When given a `String` for `::Marcel::MimeType.for` the returned value is `application/octet-stream`.
Related to:
- https://github.com/samvera-labs/bulkrax/issues/777
[1]: https://github.com/rails/marcel
> HotFix: Patching Marcel MimeType sniffing

- app/models/concerns/bulkrax/importer_exporter_behavior.rb
Prior to this commit, when we run `File.new` we were opening the file. We did not, however, close the file.
With this commit, I've leverage the `File.open` with block behavior to open and ensure that we close the file.
Related to:
https://github.com/samvera-labs/bulkrax/pull/779
https://github.com/samvera-labs/bulkrax/pull/778
https://github.com/samvera-labs/bulkrax/issues/777
> Ensuring closed file handle when testing zip file

- lib/bulkrax.rb
the older style config setup is incompatible with Rails 6, preventing support for Hyrax 4.
this is a minimal pass at extracting the config and keeping the current API.
----
there's a RuboCop rule disable in this PR:
there's some debate about the value of this style guide rule at
https://github.com/rubocop/ruby-style-guide/issues/556.
it seems in our case like using `module_function` is going to be prohibitively
hard, and i think the longer term desire is to remove both `extend Forwardable`
and `extend self`, expecting callers to just call `#config` directly. the
behavior around defaults needs to be cleaned up to make this possible, but it
seems like a bad plan to bend this implementation around (unhelpful?) style
rules for code we'd rather work on removing.
> move config to a Configurable class

- lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
This makes the default `multi_value_element_split_on` regex valid, should someone simply decide to uncomment it as-is.
> Fix multi_value_element_split_on example regex

- app/parsers/bulkrax/oai_dc_parser.rb
while troubleshooting the hyku upgrade to `v5.2.0`, @labradford and I received an error from [ImportersController#show](https://github.com/samvera-labs/bulkrax/blob/09e8d2f05aa0822f544a8545cf263013ffd52d9a/app/controllers/bulkrax/importers_controller.rb#L41) that `file_set_entry_class` was undefined for the oai dc parser
- add `#file_set_entry_class` to the oai dc parser so imports do not fail
> default-fs-entry-class

- app/parsers/bulkrax/bagit_parser.rb
while testing bagit exporting for https://github.com/scientist-softserv/atla-hyku/issues/16, I was able to complete an export...but the zip file wouldn't show up. after some debugging I noticed that `work_entries`, `collection_entries` and `file_set_entries` all came back as an empty array inside of `BagitParser#write_files`.
the change happened in #749 when we removed the `current_record_ids` method from `CsvParser`. that method was setting the `@work_ids`, `@collection_ids` and `@file_set_ids` values.
- find the correct entry type by the entry class when exporting with bagit
we don't have to worry about back porting the fix as it was just released in `v5.2.0` (latest) last week
> fix bagit exporting

- app/parsers/bulkrax/oai_dc_parser.rb
co-author: @summer-cook 
ref: https://github.com/scientist-softserv/atla_digital_library/issues/280
creating relationships through the oai parser appears to be missing since the relationships refactor. at the time I believe only atla was using it, and they had their own custom branch to work from.
`#create_relationships` isn't in the oai dc parser in `v5.2.0` either,  but since other projects may be using it now or in the future, I don't want to add it there without knowing their implementations.
> add #create_relationships to ::OaiDcParser

- app/models/bulkrax/csv_entry.rb
- ref: https://github.com/scientist-softserv/atla_digital_library/issues/295
when exporting from ATLA on the `v4-4-patch` branch, we would have an `identifier` column **and** `identifier_1` column. one would be an array, while the other would be a string
- Do not duplicate source identifier on export 
- backport `#build_system_metadata fix` from `v5.0.0` (#712)
> do-not-duplicate-source-identifier-on-export

- app/controllers/bulkrax/exporters_controller.rb
- app/controllers/bulkrax/importers_controller.rb
Prior to this commit, we did not provide a sort order to the results rendered in Bulkrax's importers and exporters show page.  The default was by ascending ID.
With this commit, we are instead sorting with the most recent first and the oldest last.
> Default ordering importers/exporters by created_at: :desc

- app/parsers/bulkrax/parser_export_record_set.rb
- spec/parsers/bulkrax/parser_export_record_set_spec.rb
The newly added method extracts logic from the file_set query, making it available throughout this module for other places where we might have a large number of IDs all `OR`-ed together.
Related to:
- https://github.com/samvera-labs/bulkrax/issues/776
- https://github.com/scientist-softserv/britishlibrary/issues/373
- https://github.com/scientist-softserv/palni-palci/pull/440
- https://github.com/samvera-labs/bulkrax/issues/775
> ♻️ Adding Bulkrax::ParserExportRecordSet.in_batches

- app/jobs/bulkrax/create_relationships_job.rb
- spec/jobs/bulkrax/create_relationships_job_spec.rb
Changes child `save!` to `update_index` and moves it to after the parent record is saved.
Parent/child relationships are stored on the parent, but indexed onto the child. A child work will not have the correct relationships saved in the index if not reindexed after the parent is saved with the relationship.
Refs https://github.com/samvera-labs/bulkrax/issues/810
> 🐛 Reindex child work after adding relationship

- app/jobs/bulkrax/create_relationships_job.rb
- lib/bulkrax.rb
With this commit we're adding two major concepts:
- Conditional locking of records (when locking is available)
- Checking that a parent_record exists before proceeding on further
checks/tests that could raise errors
Further, I've taken the liberty to move the increment failed
relationships out of the general error handling and instead to happen
only if we had a parent record; with the assumption that when we don't
have a parent, we only want to report one error instead of reporting one
error per child.
Closes: #804
- https://github.com/samvera-labs/bulkrax/issues/804
Co-authored-by: LaRita Robinson <larita@scientist.com>
> 🐛 Add record locking for create_relationships_job

- README.md
- lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
- Add missing "run migrations" step to README install instructions
- Clarify that `Bulkrax.default_work_type` needs to be a string
- Correct spell mistakes
> 📚 Add / correct documentation

- .github/workflows/test.yml
- bulkrax.gemspec
- db/migrate/20230608153601_add_indices_to_bulkrax.rb
- spec/test_app/config/database.yml
- spec/test_app/config/initializers/redis_config.rb
- spec/test_app/db/schema.rb
Note: this is a best guess of what could use indexing.  The guess is based on my recent querying.
- `add_index :bulkrax_entries, :identifier` :: because the identifier is an important concept for an import.
- `add_index :bulkrax_entries, :type` :: because filtering on the type of an entry is important.
- `add_index :bulkrax_entries, [:importerexporter_id, :importerexporter_type], name: 'bulkrax_entries_importerexporter_idx` :: this is a foreign key for the entries relationship to the importer/exporter.
- `add_index :bulkrax_pending_relationships, :parent_id` :: a foreign key
- `add_index :bulkrax_pending_relationships, :child_id`  :: a foreign key
- `add_index :bulkrax_statuses, [:statusable_id, :statusable_type], name: 'bulkrax_statuses_statusable_idx'` :: a foreign key
- `add_index …
> 🎁 Adding indices to Bulkrax Tables

- app/parsers/bulkrax/parser_export_record_set.rb
I noticed a typo when trying to export a csv:
> :lipstick: fix cause of NoMethodError due to typo

- app/views/bulkrax/importers/new.html.erb
Prior to these changes:
In Bulkrax, the Create and Validate button is affected by a bug known in the community. Within SoftServe we agreed to hide this button to reduce the confusion it’s causing amongst Bulkrax users. We will create an issue as a reminder to discuss and/or fix the functionality of this button in the future. 
Issue: #
With these changes:
After discussion, the solution we chose to implement was to add a conditional statement to the importer's new.html.erb file that hides the Create and Validate button until the bug is fixed.
<details>
<summary></summary>
ENV Variable set to true
ENV Variable set to false
ENV Variable set to violet
ENV Variable set to no value
</details>
The Create and Validate button on the importer form functions as expected.
> Fix create and validate button

- app/views/bulkrax/importers/new.html.erb
Follow up to:
- #821 
Only render button separator when needed
> 🐛 Move "|" button separator to be within conditional

- app/views/bulkrax/importers/edit.html.erb
The update importer modal was not opening in wvu hydra, likely because it used a regular link instead of a button. The button_to rails tag also didn't work as expected, so it needed to just render as a normal button. This PR fixes it so it will open in all apps
**Note**: this was tested in both wvu hydra & atla hyrax to ensure it works across both
- https://github.com/scientist-softserv/west-virginia-university/issues/65
https://share.getcloudapp.com/Z4uG1JEd
- As a user, i can click the update importer button from the update importer form. It opens to a modal, where i have several options to select how I would like to update my importer.
> Fix modal for hydra apps

- Gemfile
- app/assets/javascripts/bulkrax/application.js
- app/assets/javascripts/bulkrax/navtabs.js
Bootstrap's javascript files were not included by default and bulkrax was relying on the parent application for some of its js to work.
this PR includes bootstrap (and jquery dependency), makes sure they all load in the same order, and activates the nav tabs on the importer/show page. 
<details><summary>likely reason the tabs need to be initialized separately in this case </summary>
Bootstrap's JavaScript components, including the tabs functionality, require manual initialization in certain cases. This is because the default behavior of Bootstrap's JavaScript is to automatically initialize the components on page load. However, when using frameworks like Turbolinks or loading content dynamically, the JavaScript initialization may not occur automatically.
In your case, since you mentioned …
> Re-enables nav-tabs for hydra apps

- app/views/hyrax/dashboard/sidebar/_bulkrax_sidebar_additions.html.erb
- app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
This commit will add the `title` attribute to the list tags so when users hover over the links they will see the name of the link on the dashboard.
> 🎁 Add title attribute

- app/assets/javascripts/bulkrax/application.js
This commit reverts a previous commit where jQuery and bootstrap were added to application.js so Hydra can use them.  This caused issues in Hyku applications so Hydra is going to need to require jQuery and bootstrap in their application.js file instead.
Ref:
- https://github.com/samvera-labs/bulkrax/pull/836
> Remove jquery and bootstrap from bulkrax

- app/models/bulkrax/csv_entry.rb
- spec/models/bulkrax/csv_entry_spec.rb
Prior to this commit, when exporting a FileSet and GenericWork we'd see a "creator_1" and "creator" column.  The "creator" column might look as follows: `["Sandra Samvera"]`.  Which meant that creator was not an `ActiveTriples::Relation` (based on the prior logic).  Yet the "creator" field was stored as multi-value.  Perhaps having been previously coerced into an Array.
With this commit, we're favoring the Bulkrax parser field mapping `"join"` configuration over whether or not the object is an =ActiveTriples::Relation=.  That is to say, if you told us to join the field, we're going to do that regardless of the data we have.
Likewise, if the field's value is not an enumerable, we're not going to introduce an ordinal suffix (e.g. "creator_1" when we have a scalar creator).
In other words …
> 🐛 Normalizing export column names

- db/migrate/20210806044408_remove_unused_last_error.rb
- db/migrate/20230608153601_add_indices_to_bulkrax.rb
this doesn't actually change the function of the last migration. it just makes it work the same as all the other ones so we don't accidentally establish a new pattern.
> small pr to make all migrations skipable and updated last one to match existing pattern

- lib/bulkrax/engine.rb
Prior to this commit, the logic for finding the Hyrax in the view path was assuming a version number (e.g. `hyrax-2.`); however if the we pinned Hyrax to a branch/sha then we might have `hyrax-a`.  The result being that we pre-prended the view path into the application.  That created the conditions where the `view_paths` first element might not have been the application but instead a gem/engine.
Which means that the convention of overriding views in the application would not work.
With this commit, we're using the Hyrax's engine's root to determine the view path suffix.  Further, if Hyrax is not in the view path, we don't again inject at the beginning of the list the Bulkrax engine into the view path.
Related to:
- https://github.com/scientist-softserv/palni-palci/pull/731
- …
> 🐛 Ensuring we inject Bulkrax views before Hyrax

- app/views/bulkrax/importers/_bagit_fields.html.erb
- app/views/bulkrax/importers/_csv_fields.html.erb
- app/views/bulkrax/importers/_oai_fields.html.erb
- app/views/bulkrax/importers/_xml_fields.html.erb
This commit will add the option to set the `Institution` visibility when creating an importer.  Both `Public` and `Private` are options are already implemented.
> 🎁 Add `Institution` to importer visibility

- db/migrate/20230608153601_add_indices_to_bulkrax.rb
Add guard clauses to add_indices_to_bulkrax migration:
Not doing so produced the following error in Adventist, when trying to run migrations: `ArgumentError: Index name 'index_bulkrax_entries_on_identifier' on table 'bulkrax_entries' already exists`
> :bug: add guard clauses to add_indices_to_bulkrax migration

- app/factories/bulkrax/object_factory.rb
- app/views/bulkrax/importers/_oai_fields.html.erb
restore the ability to load the "/importers" page.
there was an extra "x" in the app/views/bulkrax/importers/_oai_fields.html.erb file. it threw a syntax error when trying to create a new importer.
<details>
<summary>error</summary>
</details>
restore our ability to properly look up works by their work_identifier
- ref: https://github.com/samvera-labs/bulkrax/issues/866
- ref:https://github.com/samvera-labs/bulkrax/issues/867
<details>
<summary>error</summary>
</details>
> 5.4.0-bug-fixes

- app/parsers/bulkrax/csv_parser.rb
Import CSV [GAM-Test004.csv](https://github.com/samvera-labs/bulkrax/files/12848386/GAM-Test004.csv) with empty model value to comet (currently using hyrax-4-rails-6 branch) will trigger NoMethodError in Bulkrax::Importers::Controller#create: undefined method `casecmp` for nil:NilCLass. 
The pull request will avoid the error.
> Avoid NoMethodError in Bulkrax::Importers::Controller#create.

- lib/bulkrax/entry_spec_helper.rb
Prior to this commit, I was not including documented examples of how to
use the spec helper methods.  Also there were private API methods that
I accidentally called in a demonstration.
So, I updated the documentation and privatized the private API methods
to help folks leverage this function.
> 📚 Update docs in preparation for best practices seminar

- app/assets/javascripts/bulkrax/navtabs.js.erb
We've recently encountered issues where some of our non-bulkrax pages with tabbed content are attempting to switch content via javascript when they are actually supposed to trigger a page reload. It appears that an event in bulkrax is being bound to all bootstrap "nav-tab" objects, and is interfering with the expected behavior. 
This PR just scopes the event binding to bulkrax related content to prevent the event from leaking to other unrelated pages. `bulkrax-nav-tab-top-margin` was the best class I could find, but I'm definitely open to suggestions.
> Nav-tabs event scoping

- app/assets/javascripts/bulkrax/navtabs.js.erb
- app/views/bulkrax/shared/_bulkrax_errors.html.erb
This commit will add logic for showing the correct tab in a Hydra application like WVU's.  We found that if we add the bootstrap require in their application.js then Blacklight's dropdown menu's stop working. However this then breaks Bulkrax tabs.  Because we're not adding bootstrap into the Hydra appilication, we mimic the behavior of the tabs function instead.
https://github.com/samvera-labs/bulkrax/assets/19597776/d5650038-fbc8-4181-982b-87cceaf76964
> 🐛 Fix tabs for Hydra application

- README.md
For compliance checklist to promote from samvera-labs to samvera
relates #876
> add Compatibility section to readme

- app/jobs/bulkrax/create_relationships_job.rb
- app/jobs/bulkrax/delete_job.rb
- app/jobs/bulkrax/export_work_job.rb
- app/jobs/bulkrax/import_collection_job.rb
- app/jobs/bulkrax/import_file_set_job.rb
- app/jobs/bulkrax/import_work_job.rb
- app/parsers/bulkrax/application_parser.rb
- spec/factories/bulkrax_exporter_runs.rb
- spec/factories/bulkrax_importer_runs.rb
- spec/jobs/bulkrax/delete_work_job_spec.rb
- spec/jobs/bulkrax/export_work_job_spec.rb
- spec/jobs/bulkrax/import_file_set_job_spec.rb
- spec/jobs/bulkrax/import_work_job_spec.rb
- spec/test_app/db/schema.rb
SQL logs before changes (using `#increment!`):
```sql
Bulkrax::ImporterRun Load (8.9ms)  SELECT  "bulkrax_importer_runs".* FROM "bulkrax_importer_runs" WHERE "bulkrax_importer_runs"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Bulkrax::ImporterRun Update All (2.5ms)  UPDATE "bulkrax_importer_runs" SET "processed_records" = COALESCE("processed_records", 0) + 1 WHERE "bulkrax_importer_runs"."id" = $1  [["id", 1]]
```
SQL logs after changes (using `#increment_counter`):
```sql
Bulkrax::ImporterRun Update All (6.5ms)  UPDATE "bulkrax_importer_runs" SET "processed_records" = COALESCE("processed_records", 0) + 1 WHERE "bulkrax_importer_runs"."id" = $1  [["id", 1]]
```
The `SELECT` statement serves no purpose since the `UPDATE` statement is atomic.
I haven't done any benchmarks on these …
> Reduce SQL calls when incrementing/decrementing run counters

- bulkrax.gemspec
This was previously pinned to make specs green. probably should have been in the gemfile instead
> unpin dry-monads. its not a dependency of bulkrax

- .rubocop.yml
- Gemfile
- app/controllers/bulkrax/importers_controller.rb
- app/factories/bulkrax/object_factory.rb
- app/models/concerns/bulkrax/import_behavior.rb
- app/parsers/bulkrax/application_parser.rb
- app/views/hyrax/dashboard/sidebar/_bulkrax_sidebar_additions.html.erb
- lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
- lib/tasks/bulkrax_tasks.rake
- spec/factories/bulkrax/object_factory_spec.rb
- spec/factories/bulkrax_object_factories.rb
- spec/models/bulkrax/object_factory_spec.rb
- spec/rails_helper.rb
This PR requires anyone with custom code that creates an ObjectFactory or that overrides the ObjectFactory#initializer or ObjectFactory#search_by_identifier methods to update their code to take in to account the new `work_identifier_search_field`
Resolves #867 and #866
> make search string used to look up objects configurable

- app/parsers/bulkrax/application_parser.rb
The chaining logic for was grabbing the first letter of a single search_field value; instead of grabbing the first value in the 'search_field' object.
To fix the problem, we cast the value of `search_field` into an array and then grab the first array element.
Related to:
- https://github.com/samvera/bulkrax/issues/890
> 🐛 Fix #work_identifier_search_field logic

- lib/bulkrax.rb
- lib/bulkrax/engine.rb
- lib/bulkrax/persistence_layer.rb
- lib/bulkrax/persistence_layer/active_fedora_adapter.rb
- lib/bulkrax/persistence_layer/valkyrie_adapter.rb
- spec/lib/bulkrax_spec.rb
At present we have not incorporated using the
`Bulkrax.persistence_adapter` into the application.  It is instead put
forward for discussion and review.
Why introduce the adapter strategy?  Because there are several instances
of Bulkrax that are installed along various points of Hyrax
versions as well as non-Hyrax versions; which means that there are some
cases where we'll be using ActiveFedora and some where we'll be moving
towards Valkyrie.
The goal of the adapter is two fold:
- Clarify and define the data interface between Bulkrax and the Main App
- Allow for ease of maintaining Bulkrax releative to varying versions of
Hyrax and Hyku; thus allowing folks to upgrade to new features of
Bulkrax without mandating an upgrade of their entire persistence
strategy.
Related to:
- …
> 🎁 Add `Bulkrax.persistence_adapter`

- lib/bulkrax.rb
This builds on a [question asked in Slack][1]
[1]: https://samvera.slack.com/archives/C03S9FS60KW/p1705681632335919
> 📚 Adding documentation for configuration

- app/services/bulkrax/factory_class_finder.rb
- lib/bulkrax.rb
- spec/lib/bulkrax_spec.rb
- spec/services/bulkrax/factory_class_finder_spec.rb
Prior to this commit, once we had a factory class name we always called `#constantize` on the string.
With this commit, we retain that default behavior by:
1. Introducing a function that does this thing
2. Exposing a configuration end-point for that function
Further, we add a looming Valkyrie convention; namely that for each legacy named model (e.g. `Work`) there will likely be a corresponding model with the Resrouce suffix (e.g. `WorkResource`).
Related to:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/125
> 🎁 Config option for coercing a factory class name

- app/models/concerns/bulkrax/dynamic_record_lookup.rb
- app/models/concerns/bulkrax/export_behavior.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/parsers/bulkrax/parser_export_record_set.rb
- spec/parsers/bulkrax/bagit_parser_spec.rb
- spec/parsers/bulkrax/csv_parser_spec.rb
- spec/support/dynamic_record_lookup.rb
Instead of direct calls to a deprecated service favor a persistence layer call; one that defines an interface.
Note this means we need to implement the methods in the Valkyrie adapter; but those should be trivial.
> ♻️ Favor Bulkrax's persistence layer

- app/factories/bulkrax/object_factory.rb
- app/jobs/bulkrax/create_relationships_job.rb
- lib/bulkrax/persistence_layer/active_fedora_adapter.rb
This will add a relationships path for Valkyrie objects.  It also will add a transactions call so set child flag will fire off in IIIF Print.
ref:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/141
Child links to parent work now, after successful job completion:
> 🧹 Make CreateRelationshipJob work for Valkyrie

- bulkrax.gemspec
Without the previously committed `require 'dry-monads'` we encounter the following error:
```
bundle exec rspec
NameError:
uninitialized constant Dry::Monads::Result::Transformer
./spec/test_app/config/application.rb:15:in `<top (required)>'
./spec/test_app/config/environment.rb:4:in `require_relative'
./spec/test_app/config/environment.rb:4:in `<top (required)>'
./spec/rails_helper.rb:8:in `<top (required)>'
./spec/parsers/bulkrax/xml_parser_spec.rb:3:in `<top (required)>'
```
The error repeats everywhere.
When I add the development dependency and remove the require, I see the same error.
So, to be clear about this development dependency, I've added it to the gemspec.
See:
- https://github.com/samvera/bulkrax/pull/900#discussion_r1480995354
- https://github.com/samvera/bulkrax/pull/900
> ⚙️ Adding dry-monads as development dependency

- app/models/bulkrax/importer.rb
- app/models/bulkrax/status.rb
- app/models/concerns/bulkrax/status_info.rb
- bulkrax.gemspec
- db/migrate/20240208005801_denormalize_status_message.rb
- lib/bulkrax.rb
- lib/tasks/bulkrax_tasks.rake
Storing the status_message on the entry will do a lot of good. It is so hard to sort and search by status right now and it just doesn't have to be. The status of an Entry is especially important. This PR also makes way for the new datatables work.
When deploying this change all objects will have the status_message "Pending" until the `bulkrax:update_status_messages` rake task is run. Call `rails bulkrax:update_status_messages` to do so. It touches every entry, so it could take a little while ☕ 
These should be kept in sync pretty faithully, but we're providing a rake task for setup and just in case.
> Denormalize Status Message to that Entry Look Up Can Be Fast

- app/factories/bulkrax/object_factory.rb
- app/factories/bulkrax/valkyrie_object_factory.rb
- app/jobs/bulkrax/delete_job.rb
- app/parsers/bulkrax/application_parser.rb
- spec/jobs/bulkrax/delete_work_job_spec.rb
The DeleteJob previously was not working with the old factory#find method because when it is doing a delete action, the parsed_metadata does not get generated like during a regular import.  Because of this, the #search_by_identifier method fails to find anything because we don't have a `work_identifier` field which would have came from the parsed_metadata.  So instead, we are using the new class method .find which will take an id (which we find on the raw_metadata) to find the object.  We make sure to reindex and publish the action to any relevant listeners.
> 🧹 Make DeleteJob work wth new class method .find

- app/models/bulkrax/csv_entry.rb
- spec/test_app/config/application.rb
> Strip out all special characters from csv headers

- app/assets/javascripts/bulkrax/importers.js.erb
- app/assets/stylesheets/bulkrax/import_export.scss
- app/controllers/bulkrax/entries_controller.rb
- app/controllers/bulkrax/importers_controller.rb
- app/models/bulkrax/importer.rb
- app/parsers/bulkrax/application_parser.rb
- app/views/bulkrax/importers/_csv_fields.html.erb
Adds an option to select existing entries by status when updating an importer. The source file will not be reread, the works simply get built or removed and built again.
[screenshot](https://share.zight.com/RBuklK2w)
> Select existing entries for update

- app/parsers/bulkrax/application_parser.rb
- db/migrate/20240209070952_update_identifier_index.rb
- spec/test_app/db/schema.rb
There were previously cases where a new importer would either steal an existing importers entry or it would update the old entry and not show it when viewing that importer. This fixes that by scoping entry identifiers to the importer or exporter that created them.
> For every importer / record combo there should be exactly one entry

- app/assets/javascripts/bulkrax/datatables.js
- app/controllers/bulkrax/exporters_controller.rb
- app/controllers/concerns/bulkrax/datatables_behavior.rb
- app/views/bulkrax/exporters/index.html.erb
- app/views/bulkrax/exporters/show.html.erb
- app/views/bulkrax/importers/show.html.erb
- app/views/bulkrax/shared/_entries_tab.html.erb
- config/routes.rb
Mimicking the importers show page, this change adds support for the datatables.js to the exporters show page.
> Fix exporters show page - 2

- app/jobs/bulkrax/create_relationships_job.rb
- app/jobs/bulkrax/delete_job.rb
- app/jobs/bulkrax/download_cloud_file_job.rb
- app/jobs/bulkrax/import_collection_job.rb
- app/jobs/bulkrax/import_file_set_job.rb
- app/jobs/bulkrax/import_work_job.rb
- app/jobs/bulkrax/importer_job.rb
- lib/bulkrax.rb
Given that Hyrax provides a mechanism for specifying a queue name, we should echo that configuration, but also provide our own configuration as well as the same fallback.
> ♻️ Favor configuration over hard-coding

- app/assets/javascripts/bulkrax/exporters.js
- app/controllers/concerns/bulkrax/datatables_behavior.rb
- app/views/bulkrax/exporters/_form.html.erb
This commit will add the `hidden` class back in addition to the `d-none` class.  This way older Hyku/Hyrax applications can still use it without unintended effects.  Also, adding a turbolinks false to the edit exporter link because the buttons on the form page was not working without a refresh.
> 🐛 Fix exporter page for Bootstrap 3 applications

- app/parsers/bulkrax/parser_export_record_set.rb
- lib/bulkrax.rb
- spec/parsers/bulkrax/parser_export_record_set_spec.rb
For several years Hyrax has index `file_set_ids_ssim` as a verbatim copy of `member_ids_ssim`.  With Hyrax 5, we're removing the `file_set_ids_ssim` from indexing; And given that it's been a verbatim copy since 2017 or so, it's relatively safe to assume that we can favor, without application impact, the `member_ids_ssim` over the `file_set_ids_ssim` value.
It would be nice to have `file_set_ids_ssim` but not as a verbatim copy. Someday, we might have nice things.
In the case of Bulkrax, given that we don't require Hyrax, we need to have a configurable option as well as one that is a consistent fallback to what came before.
Related to:
- https://github.com/samvera/hyrax/pull/6513
- https://github.com/samvera/hyrax/commit/7108409c619cd2ba4ae8c836b9f3b429a7e9837b
> ♻️ Favor member_ids_ssim over file_set_ids_ssim

- app/matchers/bulkrax/application_matcher.rb
- app/models/bulkrax/csv_entry.rb
- app/models/bulkrax/importer.rb
- app/models/bulkrax/oai_entry.rb
- app/models/bulkrax/rdf_entry.rb
- app/models/bulkrax/xml_entry.rb
- app/models/concerns/bulkrax/export_behavior.rb
- app/models/concerns/bulkrax/importer_exporter_behavior.rb
- app/parsers/bulkrax/application_parser.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
- app/parsers/bulkrax/xml_parser.rb
- bulkrax.gemspec
- lib/bulkrax.rb
- spec/parsers/bulkrax/bagit_parser_spec.rb
skip rdf or bagit parsers / entries if those gems are not present
Fixes #886
> move various requires to a central location lib/bulkrax.rb,

- app/views/bulkrax/entries/show.html.erb
Given our effort at lazy migration in Bulkrax we want to do a bit more sniffing regarding the objects.  This is not quite adequate for the general case of Collections but it is an improvement.
Ideally we should be interrogating the class and asking `klass.collection?` but there are some confounding edge cases around routing that we are in this pickle.
```ruby
irb(main):002:0> CollectionResource.model_name
=>
@collection="collections",
@element="collection",
@human="Collection",
@i18n_key=:collection,
@klass=CollectionResource,
@name="CollectionResource",
@param_key="collection",
@plural="collections",
@route_key="collections",
@singular="collection",
@singular_route_key="collection">
irb(main):003:0> Collection.model_name
=>
@collection="collections",
@element="collection", …
```
> ♻️ Favor asking about model_name over class

- app/controllers/bulkrax/importers_controller.rb
- app/jobs/bulkrax/download_cloud_file_job.rb
- app/jobs/bulkrax/importer_job.rb
- app/parsers/bulkrax/bagit_parser.rb
- app/parsers/bulkrax/csv_parser.rb
🎁 Download Cloud Files later
This commit will bring in changes from `5.3.1-british_library` to move
the download of cloud files to a background job
> Download cloud files later

- app/parsers/bulkrax/application_parser.rb
The remove and rerun option was throwing a NoMethodError for `not` on a `Arel::Attributes::Attribute` object.
> 🐛 Fix batch remove and rerun

- lib/bulkrax.rb
I'm unclear why we were defining methods on the conf instance; especially given that these exist on the configuration.
With this refactor, we're favoring using the Configuration object as the container.
> ♻️ Move method and remove single instance definition

- app/assets/javascripts/bulkrax/datatables.js
- app/controllers/concerns/bulkrax/datatables_behavior.rb
- app/views/bulkrax/entries/_parsed_metadata.html.erb
- app/views/bulkrax/entries/_raw_metadata.html.erb
- app/views/bulkrax/importers/_browse_everything.html.erb
- app/views/bulkrax/importers/show.html.erb
- app/views/bulkrax/importers/upload_corrected_entries.html.erb
- app/views/bulkrax/shared/_bulkrax_errors.html.erb
- app/views/bulkrax/shared/_bulkrax_field_mapping.html.erb
- spec/controllers/concerns/bulkrax/datatables_behavior_spec.rb
Hyrax 4+ applications use font awesome and not glyphicon. This commit will convert all glyphicon to font awesome. 
Previous versions of Hyrax use both glyphicon and font awesome so this should be backwards compatible.
> 🎁 Change glyphicon to font awesome

- db/migrate/20240307053156_add_index_to_metadata_bulkrax_identifier.rb
- spec/test_app/db/schema.rb
This significantly speeds up queries like [this one](https://github.com/WGBH-MLA/ams/blob/c27625be06778f958cde0ffd7af802b69def4c78/app/services/hyrax/custom_queries/find_by_bulkrax_identifier.rb#L25-L30). 
Originally implemented by @orangewolf in GBH AMS.
> Index :bulkrax_identifier metadata in :orm_resources

- app/jobs/bulkrax/import_file_set_job.rb
This commit will fix the functionality for adding a FileSet row in the CSV to add additional metadata to FileSets.  The problem was located in `Bulkrax::ObjectFactory#create_file_set`.  When it tries to find a record, it actually comes back as a `FalseClass` because of the new logic introduced recently which breaks further down.  If we add raise an error in our `Bulkrax::ImportFileSetJob#find_parent_record` which is at a higher point than before, then we can requeue the job and check again. If the parent record is created by then, we will execute the rest of the job.
Issue: 
- https://github.com/scientist-softserv/hykuup_knapsack/issues/216
This fix was made in the PALs repo, here is the CSV used:
[pals-with-file-row.zip](https://github.com/samvera/bulkrax/files/15276997/pals-with-file-row …
> 🐛 Fix FileSet csv rows for AF imports

- lib/bulkrax/version.rb
Cutting a 8.1.0 release which contains bug fixes and the embargo support feature ...
d8f9b85 — Downgraded ActiveRecord method version from 6.1 to 5.2 - Fixes #948 (#949) Dan Kerchner, (2024-05-28)  (HEAD -> main, origin/main, origin/HEAD)
0de8ee0 — 🐛 Fix FileSet csv rows for AF imports (#954) Kirk Wang, (2024-05-10) 
bf7bc5c — :bug: [I951] false object import bug (#952) Shana Moore, (2024-04-22) 
855ce39 — I1010 embargo lease support (#950) Shana Moore, (2024-04-17)
> Bump version for minor release

- app/controllers/bulkrax/importers_controller.rb
- app/models/bulkrax/importer.rb
- app/views/bulkrax/importers/show.html.erb
- config/routes.rb
It can be useful to be able to download the file that was originally uploaded for an import. It won't work in all cases (such as OAI) but it will work in most cases.
> add support for downloading the original file

- app/factories/bulkrax/object_factory.rb
> fix a memory leak when copying large files by using the hyrax uploader

- app/views/bulkrax/importers/_csv_fields.html.erb
This was contributed back per PALNI PALCI. Since it's possible to override whatever setting the user selects at the form level, help text is provided. If the visibility is declared at the CSV level, the visibility selected at the form level will be ignored.
Issue:
- https://github.com/scientist-softserv/palni_palci_knapsack/issues/84
> i84 - update visibility label and help text

- app/factories/bulkrax/valkyrie_object_factory.rb
object equals nil here. but @object returned what we were looking for. Update code so that we save @object instead of saving nil, which rightfully raised errors.
Related issue:
- https://github.com/scientist-softserv/palni_palci_knapsack/issues/91
Tested from Hyku to verify this works: 
[split-embargo-hyku.zip](https://github.com/user-attachments/files/15903184/split-embargo-hyku.zip)
> i91 - saving nil object caused errors

- app/models/bulkrax/importer.rb
When testing the OAI importer on Adventist valkyrie, we received the following error. The error was caused because oai imports from a feed, so no original file exists. When checking, instead of returning false it returned nil, and thus caused a TypeError. 
related: 
- https://github.com/scientist-softserv/adventist_knapsack/issues/723
The site will not break when an original file doesn't exist.
970ad45906b1db6f02f19679f723318da4c22418
- Centralized the import_file_path logic into a separate method
- Resolved TypeError caused by nil values when checking file existence
- Improved code readability and maintainability
> :bug: Refactor: Fix file path access to prevent error

- app/factories/bulkrax/valkyrie_object_factory.rb
- db/migrate/20240806161142_add_file_name_to_uploaded_files.rb
Previously this code strictly downloaded from s3 buckets. This was limiting, and expands the ability to import remote files without s3, and override thumbnail urls if one is provided.
Issue: 
- https://github.com/scientist-softserv/adventist_knapsack/issues/708
> :broom: expands the ability to upload remote_files for valkyrie

- app/factories/bulkrax/valkyrie_object_factory.rb
Handles situation where the csv has a thumbnail_url but no related_url to use as remote files.
Previously threw an error: `NoMethodError - undefined method + for nil:NilClass`
> Allow for only thumbnail url in csv

- app/models/concerns/bulkrax/has_matchers.rb
When the term Identifier is part of the metadata and used as source_identifier, it resulted in the value getting put into the metadata twice. Calling uniq! on the array removes any duplicate metadata, as there should never be a reason for the same metadata to be on a record twice.
> Prevent metadata duplication

- app/jobs/bulkrax/create_relationships_job.rb
small refactors to the create relationship job to make rerunning a relationship create easy.
> Ability to rerun relationship create job

- app/factories/bulkrax/valkyrie_object_factory.rb
Attributes were not consistently using the same types of keys. By converting to HashWithIndifferentAccess first, we ensure that we find the keys we are looking for.
Refs https://github.com/scientist-softserv/adventist_knapsack/issues/770
> Ensure HashWithIndifferentAccess

- app/factories/bulkrax/valkyrie_object_factory.rb
Prior to this fix, when reimporting (where we have no remote files), we were getting [nil] rather than [] for the files. This resulted in an error `Error: NoMethodError - undefined method '[]' for nil:NilClass`
This PR corrects the logic for gathering the remote files to be imported.
> Fix for no remote files

- .github/workflows/test.yml
- app/assets/javascripts/bulkrax/datatables.js
- app/models/bulkrax/importer.rb
- app/models/bulkrax/importer_run.rb
- db/migrate/20240916182737_add_last_imported_at_to_bulkrax_importers.rb
- db/migrate/20240916182823_add_next_import_at_to_bulkrax_importers.rb
- lib/tasks/bulkrax_tasks.rake
7d985dda63bb027fb9f1cb7416709a54a420968a
This commit will fix the sorting error that happens when the user is on
the importers index and attempts to sort by the last run or next run. We
add some migrations to add fields that the datatables can use so it can
sort properly. Previously, this was not working because the
last_imported_at and next_import_at fields were actually methods on the
importer_run object and not the importer object.  We are adding a few
callbacks to the importer and importer_run models to ensure that the
fields are properly set when they are called from either the web or the
worker.
Ref:
- https://github.com/samvera/bulkrax/issues/956
https://github.com/user-attachments/assets/65c5b70e-5c9a-40ac-897d-c417fe24b636
aca33e568c06236c5652a0e500da33c5d46cba10
CI was getting …
> 🐛 Fix importers sorting for last run and next run

- app/factories/bulkrax/valkyrie_object_factory.rb
This adds import_url to the attributes for creating a Valkyrized file set.
To actually save the import_url on a file set, the application needs to:
- add import_url to the file_set metadata attributes in your app
- decorate Hyrax::WorkUploadsHandler to add import_url to the file_set_args method
Additionally it defaults local_files to an empty array in case there are no local files.
> Add import_url to file set attributes

- lib/bulkrax.rb
Using `#try` on `:internal_resource` can yield unexpected results. If the method is undefined, it can return a truthy value instead of the typical `nil`.
E.g.
```ruby
Hyrax::FileSet.try(:internal_resource) || 'hi'
=> #<Dry::Types::Result::Failure input=:internal_resource error=#<Dry::Struct::Error: [Hyrax::FileSet.new] can't convert Symbol into Hash>>
```
E.g. 
```ruby
Bulkrax.collection_model_internal_resource
=> #<Dry::Types::Result::Failure input=:internal_resource error=#<Dry::Struct::Error: [CollectionResource.new] can't convert Symbol into Hash>>
```
This was discovered while trying to export Valkyrie Resources from HykuUP (see screenshot) 
<details><summary>Screenshot</summary>
</details>
> Avoid false positive from `.try(:internal_resource)`

- app/controllers/concerns/bulkrax/datatables_behavior.rb
- app/models/bulkrax/status.rb
- db/migrate/20241203010707_entry_error_denormalization.rb
- db/migrate/20241205212513_faster_first_entry.rb
- lib/tasks/bulkrax_tasks.rake
- spec/test_app/db/schema.rb
we lose the error message in the title, you have to click through to see it but page speeds go up 100x.
Release note:
Requires running `rails bulkrax:update_status_messages` for error messages to display.
> speed up entries display by no longer looking at all the status objects

- app/models/concerns/bulkrax/export_behavior.rb
- app/parsers/bulkrax/csv_parser.rb
- app/parsers/bulkrax/parser_export_record_set.rb
Fixes issues with FileSets exporting in Valkyrie versions of Hyrax/Hyku
refs #990 
- demodulized the solr fileset call and wrapped it in quotes so that it doesn't throw solr errors.
- added fileset name call for valkyrie. verifies mime type like in the original non-valkyrie version. (this was previously noted as possibly not working with valkyrie. the errors didn't show because the initial solr error prevented filesets from being found in solr in the first place)
> Fixes issues with filesets exporting in Valkyrie

- bulkrax.gemspec
This commit will bump the Bagit dependency to 0.6.0 which allows for Ruby 3.3 support.
https://github.com/tipr/bagit/releases
Nothing in the release indicate a breaking change.
> ⬆️ Up Bagit dependency to 0.6.0

- db/migrate/20240806161142_add_file_name_to_uploaded_files.rb
This commit will check if uploaded_files is a table before adding the file_name column to it.  In a Hydra application, it is not so this was crashing.
> Add guard to uploaded_files migration

- app/jobs/bulkrax/export_work_job.rb
There are times when the last entries of an export have an old version of an ExporterRun and they think there are still are enqueued record when other threads have already processed them. This causes the ExporterRun to potentially never update the status and it appears to never complete (stuck in pending state, despite the export being finished). This PR reloads the ExporterRun before checking to make sure it is up to date and the status update runs.
> fix race condition for statuses on export

- app/factories/bulkrax/valkyrie_object_factory.rb
This method is 100% compatible with non-flexible metadata Valkyrie objects so does not require guards or flags.
> update the bulkrax factory to support flexible metadata while maintaining non-flexi support

- app/factories/bulkrax/object_factory_interface.rb
Changed in Hyrax 4 valkyrie support (#872). several bugs around this change have been guarded against, but a full audit was done and there is nothing that requires this method to continue to return false and several places that still expect it to be nil. So we are reverting to nil when an object isnt found in the factory
> Revert ObjectFactory#find method returning false instead of nil on missing object

- Gemfile
- app/assets/javascripts/bulkrax/importers.js.erb
previously the edit form would display all parser fields regardless if which parser was selected. This also was preventing a user form attaching a file.
2356df259189c0b5c7e0339af8379dc1ca4ae956
The form initialization check was previously only looking for new forms
(#new_importer), causing the JavaScript field visibility logic to be
skipped entirely on edit pages. This meant parser-specific fields weren't
being properly hidden/shown when editing existing importers.
Added .edit_importer to the form check to ensure the field visibility
logic runs on both new and edit forms.
93ddfaed76876d2be956955eee27af60ede483ac
- Addresses logger dependency removal in concurrent-ruby v1.3.5
- Ensures compatibility with Rails versions before 7.1
> :bug: Fix parser field visibility on importer edit form

- app/parsers/bulkrax/csv_parser.rb
Prior to this commit, if an importer has a CSV file as an attachment, the importer would fail because it would try to parse the attached CSV as the importer CSV.  This commit will add a condition to only look for a CSV file that is NOT in the `/files` directory.
Ref:
- https://github.com/samvera/bulkrax/issues/989
> 🐛 Fix importing CSV as attachment

- app/assets/javascripts/bulkrax/datatables.js
- app/views/bulkrax/importers/show.html.erb
- app/views/bulkrax/shared/_entries_tab.html.erb
- config/locales/bulkrax.en.yml
4fb1a9a9bc3828f4e44395029ba9d89392f2bd96
This commit will align the download buttons on the importer pages with
the header.  Also, the table width was funky so that is also fixed.
https://github.com/user-attachments/assets/e6f21af9-00f5-46f3-a5d2-fec0759832be
https://github.com/user-attachments/assets/a1c9edc2-26cf-4e0e-834a-5ce969d73fdd
786fb464a3e140825ce99bad92c68043c907c427
This commit will add missing translations for the importer show page
table.
8ff8d77fa6a480dcca5c989df170f560167cc466
In Bootstrap 4 we now use d-none.
> 🐛 Cleaning up UI on importers show

- app/models/bulkrax/importer.rb
- app/parsers/bulkrax/application_parser.rb
We discovered a bug with the previous updates to
the `#importer_unzip_path` method where when the method is being called to create a path, it returns `nil` because the path does not exist and the whole reason why we are calling the method is to create the path.
We add a `mkdir` argument to differentiate between when we're looking up the path vs wanting to create it.
> 🐛 Fix `#importer_unzip_path` logic

- Gemfile
- app/factories/bulkrax/valkyrie_object_factory.rb
Bulkrax jobs were continuing without reporting an error, with nothing appearing in the logs.
This commit causes file errors to be reported in the importer even though the job will end normally.
<details>
</details>
> Bulkrax should show errors when remote urls are not valid 

- app/parsers/bulkrax/application_parser.rb
This fixes a bug where `File.directory?` was being called on `nil` because the unless statement was running before the `Dir.mkdir` statement, which was supposed to create the new dir
> pass mkdir when first referencing unzip path in `#untar`

- app/factories/bulkrax/object_factory.rb
- app/factories/bulkrax/valkyrie_object_factory.rb
- app/matchers/bulkrax/application_matcher.rb
- app/services/hyrax/custom_queries/find_by_source_identifier.rb
- app/services/wings/custom_queries/find_by_source_identifier.rb
- app/views/bulkrax/entries/show.html.erb
- lib/bulkrax/engine.rb
https://github.com/samvera/bulkrax/issues/1024
This commit allows a CSV importer edit to find the object to edit by the identifier rather than requiring the class. 
If a CSV did not include the model, the edit would create new valkyrie works using the defined default model. This resulted in two works in the resource table, with only the newer one indexed. The new work would only contain the metadata present in the edit CSV. The prior work was left untouched.
The source identifier alone is adequate to find the object to edit, and the importer view shows the correct model name when it links to the edited object.
(Note that it still shows the default type above the raw and parsed metadata)
<details>
<summary>Screenshot</summary>
</details>
> Bulkrax editing without model

- Gemfile
- app/factories/bulkrax/object_factory_interface.rb
Issue:
- https://github.com/notch8/wvu_knapsack/issues/42
**Problem:**
When importing objects (Collections, Works) using the Valkyrie backend in Hyrax, duplicate database records were being created for a single entry. This occurred because the `Bulkrax::ValkyrieObjectFactory`'s internal reference to the object (`@object`) was not updated after the primary Hyrax save transaction (e.g., `change_set.create_collection` or `change_set.create_work`) completed successfully within the `create` method.
Consequently, the subsequent call to `apply_depositor_metadata` within the same `create` method operated on the original, stale, in-memory object which still appeared as "new" (no ID, `persisted? == false`). This caused `Hyrax.persister.save(resource: @object)` within `apply_depositor_metadata` to …
> 🐛 [i41] - fix(ValkyrieObjectFactory): Prevent duplicate object creation

- app/factories/bulkrax/valkyrie_object_factory.rb
- app/jobs/bulkrax/create_relationships_job.rb
- spec/factories/bulkrax/pending_relationships.rb
- spec/jobs/bulkrax/create_relationships_job_spec.rb
https://github.com/samvera/bulkrax/issues/1027
Bug fixes:
- Refactor the `save!` method in the `valkyrie_object_factory` - the resources respond to save so they were being saved directly by calling save rather than by using the persister. This *should* behave the same way, since we include `Hyrax::ArResource`, but ideally `save` is a fallback, not the default.
- Corrects event notifications so events are sent and event jobs do not fail.
- Correct update of Bulkrax::PendingRelationship entry, setting with an appropriate error message. 
- Fixes finding of the child record to finding only within the given importer run.
- Refactors the CreateRelationshipsJob to lock child records when necessary, to ensure that concurrent jobs do not interfere with each other. However, the locking still seemed …
> Fix relationship race condition

- app/parsers/bulkrax/application_parser.rb
This change updates the Bulkrax ApplicationParser to enqueue a ScheduleRelationshipsJob when an importer is edited and rerun. This allows for the import process to appropriately schedule relationships during a rerun as it does during the initial import.
When editing an importer and selecting "current entries" along with any of the checkbox options, the relationships are ignored.
When editing an importer and selecting "current entries" along with any of the checkbox options, ScheduleRelationshipsJob gets enqueued and relationships are added.
> Submit ScheduleRelationshipsJob with reruns

- app/factories/bulkrax/object_factory.rb
- app/factories/bulkrax/valkyrie_object_factory.rb
- app/jobs/bulkrax/delete_job.rb
- app/models/bulkrax/csv_entry.rb
- app/parsers/bulkrax/csv_parser.rb
- app/services/bulkrax/factory_class_finder.rb
- app/views/bulkrax/entries/show.html.erb
- spec/jobs/bulkrax/delete_work_job_spec.rb
- spec/models/bulkrax/oai_entry_spec.rb
- spec/services/bulkrax/factory_class_finder_spec.rb
- fixes method `find_by_id`: This method was failing because it tried to use the find class method on an instance. This caused a silent deletion failure, where the importer reported success but the object was not deleted. It also caused the show page to be broken.
- adds another way to find the class from an entry The FactoryClassFinder did not find the class for deletions and other cases where the metadata was not parsed. This resulted in a fallback to the default work class.
- handles situations causing entry show page errors
> Handle deletion & other issues with Valkyrie objects

- app/models/bulkrax/csv_entry.rb
- app/models/concerns/bulkrax/file_set_entry_behavior.rb
- app/parsers/bulkrax/csv_parser.rb
- spec/models/bulkrax/csv_entry_spec.rb
- spec/models/bulkrax/csv_file_set_entry_spec.rb
- Raise specific errors (when they are knowable), so that we can use more targeted error handling in future.
- Add more error handling testing
- Also remove some code that has been dead for 3 years.
Existing code that rescues StandardError will still work, since all of these custom errors inherit from StandardError.
> Raise specific errors

- app/factories/bulkrax/valkyrie_object_factory.rb
- app/jobs/bulkrax/create_relationships_job.rb
- spec/models/bulkrax/valkyrie_object_factory_spec.rb
Refs https://github.com/notch8/hykuup_knapsack/issues/454
Use transaction on parent_object to update the parent_object with the file set in the Valkyrie adapter.
Depends on https://github.com/samvera/hyrax/pull/7213 to allow setting the :bulkrax_identifier on the FileSet, so that it can be re-found by the importer.
> Get uploading a FileSet working on Valkyrie 
